package org.boot.service.core.dao.base;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.boot.facede.core.model.Org;
import org.boot.facede.core.model.OrgCriteria;
import org.boot.service.core.dao.extension.OrgExtensionMapper;

@Mapper
public interface OrgMapper extends OrgExtensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    long countByExample(OrgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int deleteByExample(OrgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int deleteByPrimaryKey(String vcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int insert(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int insertSelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    List<Org> selectByExampleWithRowbounds(OrgCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    List<Org> selectByExample(OrgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    Org selectByPrimaryKey(String vcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") Org record, @Param("example") OrgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int updateByExample(@Param("record") Org record, @Param("example") OrgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int updateByPrimaryKeySelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int updateByPrimaryKey(Org record);
}