package org.boot.service.core.dao.base;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.boot.facede.core.model.User;
import org.boot.facede.core.model.UserCriteria;
import org.boot.service.core.dao.extension.UserExtensionMapper;

@Mapper
public interface UserMapper extends UserExtensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    long countByExample(UserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int deleteByExample(UserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int deleteByPrimaryKey(String vcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    List<User> selectByExampleWithRowbounds(UserCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    List<User> selectByExample(UserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    User selectByPrimaryKey(String vcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int updateByExample(@Param("record") User record, @Param("example") UserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    int updateByPrimaryKey(User record);
}