package org.boot.service.activiti.dao.base;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.boot.facede.activiti.model.Application;
import org.boot.facede.activiti.model.ApplicationCriteria;
import org.boot.service.activiti.dao.extension.ApplicationExtensionMapper;

@Mapper
public interface ApplicationMapper extends ApplicationExtensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    long countByExample(ApplicationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int deleteByExample(ApplicationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int deleteByPrimaryKey(String vcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int insert(Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int insertSelective(Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    List<Application> selectByExampleWithRowbounds(ApplicationCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    List<Application> selectByExample(ApplicationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    Application selectByPrimaryKey(String vcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") Application record, @Param("example") ApplicationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByExample(@Param("record") Application record, @Param("example") ApplicationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByPrimaryKeySelective(Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByPrimaryKey(Application record);
}