package org.boot.service.activiti.dao.base;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.boot.facede.activiti.model.ApproveInfo;
import org.boot.facede.activiti.model.ApproveInfoCriteria;
import org.boot.service.activiti.dao.extension.ApproveInfoExtensionMapper;

@Mapper
public interface ApproveInfoMapper extends ApproveInfoExtensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    long countByExample(ApproveInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int deleteByExample(ApproveInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int deleteByPrimaryKey(Long loId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int insert(ApproveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int insertSelective(ApproveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    List<ApproveInfo> selectByExampleWithBLOBsWithRowbounds(ApproveInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    List<ApproveInfo> selectByExampleWithBLOBs(ApproveInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    List<ApproveInfo> selectByExampleWithRowbounds(ApproveInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    List<ApproveInfo> selectByExample(ApproveInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    ApproveInfo selectByPrimaryKey(Long loId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") ApproveInfo record, @Param("example") ApproveInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ApproveInfo record, @Param("example") ApproveInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByExample(@Param("record") ApproveInfo record, @Param("example") ApproveInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByPrimaryKeySelective(ApproveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ApproveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByPrimaryKey(ApproveInfo record);
}