package org.boot.service.activiti.dao.base;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.boot.facede.activiti.model.Template;
import org.boot.facede.activiti.model.TemplateCriteria;
import org.boot.service.activiti.dao.extension.TemplateExtensionMapper;

@Mapper
public interface TemplateMapper extends TemplateExtensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_TEMPLATE
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    long countByExample(TemplateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_TEMPLATE
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int deleteByExample(TemplateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_TEMPLATE
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int deleteByPrimaryKey(String vcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_TEMPLATE
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int insert(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_TEMPLATE
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int insertSelective(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_TEMPLATE
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    List<Template> selectByExampleWithRowbounds(TemplateCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_TEMPLATE
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    List<Template> selectByExample(TemplateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_TEMPLATE
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    Template selectByPrimaryKey(String vcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_TEMPLATE
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") Template record, @Param("example") TemplateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_TEMPLATE
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByExample(@Param("record") Template record, @Param("example") TemplateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_TEMPLATE
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByPrimaryKeySelective(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_TEMPLATE
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    int updateByPrimaryKey(Template record);
}