package org.boot.facede.privilege.model;

import java.io.Serializable;

public class Button implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BUTTON.BUTTONID
     *
     * @mbggenerated
     */
    private String buttonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BUTTON.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BUTTON.QX_NAME
     *
     * @mbggenerated
     */
    private String qxName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BUTTON.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SYS_BUTTON
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BUTTON.BUTTONID
     *
     * @return the value of T_SYS_BUTTON.BUTTONID
     *
     * @mbggenerated
     */
    public String getButtonid() {
        return buttonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BUTTON.BUTTONID
     *
     * @param buttonid the value for T_SYS_BUTTON.BUTTONID
     *
     * @mbggenerated
     */
    public void setButtonid(String buttonid) {
        this.buttonid = buttonid == null ? null : buttonid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BUTTON.NAME
     *
     * @return the value of T_SYS_BUTTON.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BUTTON.NAME
     *
     * @param name the value for T_SYS_BUTTON.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BUTTON.QX_NAME
     *
     * @return the value of T_SYS_BUTTON.QX_NAME
     *
     * @mbggenerated
     */
    public String getQxName() {
        return qxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BUTTON.QX_NAME
     *
     * @param qxName the value for T_SYS_BUTTON.QX_NAME
     *
     * @mbggenerated
     */
    public void setQxName(String qxName) {
        this.qxName = qxName == null ? null : qxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BUTTON.BZ
     *
     * @return the value of T_SYS_BUTTON.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BUTTON.BZ
     *
     * @param bz the value for T_SYS_BUTTON.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUTTON
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", buttonid=").append(buttonid);
        sb.append(", name=").append(name);
        sb.append(", qxName=").append(qxName);
        sb.append(", bz=").append(bz);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUTTON
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Button other = (Button) that;
        return (this.getButtonid() == null ? other.getButtonid() == null : this.getButtonid().equals(other.getButtonid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getQxName() == null ? other.getQxName() == null : this.getQxName().equals(other.getQxName()))
            && (this.getBz() == null ? other.getBz() == null : this.getBz().equals(other.getBz()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUTTON
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getButtonid() == null) ? 0 : getButtonid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getQxName() == null) ? 0 : getQxName().hashCode());
        result = prime * result + ((getBz() == null) ? 0 : getBz().hashCode());
        return result;
    }
}