package org.boot.facede.privilege.model;

import java.io.Serializable;

public class Menu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.MENUID
     *
     * @mbggenerated
     */
    private Long menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.MENUNAME
     *
     * @mbggenerated
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.MENUURL
     *
     * @mbggenerated
     */
    private String menuurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.PARENTID
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.MENUORDER
     *
     * @mbggenerated
     */
    private String menuorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.MENUICON
     *
     * @mbggenerated
     */
    private String menuicon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.MENUTYPE
     *
     * @mbggenerated
     */
    private String menutype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.MENUSTATE
     *
     * @mbggenerated
     */
    private Short menustate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SYS_MENU
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.MENUID
     *
     * @return the value of T_SYS_MENU.MENUID
     *
     * @mbggenerated
     */
    public Long getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.MENUID
     *
     * @param menuid the value for T_SYS_MENU.MENUID
     *
     * @mbggenerated
     */
    public void setMenuid(Long menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.MENUNAME
     *
     * @return the value of T_SYS_MENU.MENUNAME
     *
     * @mbggenerated
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.MENUNAME
     *
     * @param menuname the value for T_SYS_MENU.MENUNAME
     *
     * @mbggenerated
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.MENUURL
     *
     * @return the value of T_SYS_MENU.MENUURL
     *
     * @mbggenerated
     */
    public String getMenuurl() {
        return menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.MENUURL
     *
     * @param menuurl the value for T_SYS_MENU.MENUURL
     *
     * @mbggenerated
     */
    public void setMenuurl(String menuurl) {
        this.menuurl = menuurl == null ? null : menuurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.PARENTID
     *
     * @return the value of T_SYS_MENU.PARENTID
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.PARENTID
     *
     * @param parentid the value for T_SYS_MENU.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.MENUORDER
     *
     * @return the value of T_SYS_MENU.MENUORDER
     *
     * @mbggenerated
     */
    public String getMenuorder() {
        return menuorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.MENUORDER
     *
     * @param menuorder the value for T_SYS_MENU.MENUORDER
     *
     * @mbggenerated
     */
    public void setMenuorder(String menuorder) {
        this.menuorder = menuorder == null ? null : menuorder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.MENUICON
     *
     * @return the value of T_SYS_MENU.MENUICON
     *
     * @mbggenerated
     */
    public String getMenuicon() {
        return menuicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.MENUICON
     *
     * @param menuicon the value for T_SYS_MENU.MENUICON
     *
     * @mbggenerated
     */
    public void setMenuicon(String menuicon) {
        this.menuicon = menuicon == null ? null : menuicon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.MENUTYPE
     *
     * @return the value of T_SYS_MENU.MENUTYPE
     *
     * @mbggenerated
     */
    public String getMenutype() {
        return menutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.MENUTYPE
     *
     * @param menutype the value for T_SYS_MENU.MENUTYPE
     *
     * @mbggenerated
     */
    public void setMenutype(String menutype) {
        this.menutype = menutype == null ? null : menutype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.MENUSTATE
     *
     * @return the value of T_SYS_MENU.MENUSTATE
     *
     * @mbggenerated
     */
    public Short getMenustate() {
        return menustate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.MENUSTATE
     *
     * @param menustate the value for T_SYS_MENU.MENUSTATE
     *
     * @mbggenerated
     */
    public void setMenustate(Short menustate) {
        this.menustate = menustate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_MENU
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuid=").append(menuid);
        sb.append(", menuname=").append(menuname);
        sb.append(", menuurl=").append(menuurl);
        sb.append(", parentid=").append(parentid);
        sb.append(", menuorder=").append(menuorder);
        sb.append(", menuicon=").append(menuicon);
        sb.append(", menutype=").append(menutype);
        sb.append(", menustate=").append(menustate);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_MENU
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Menu other = (Menu) that;
        return (this.getMenuid() == null ? other.getMenuid() == null : this.getMenuid().equals(other.getMenuid()))
            && (this.getMenuname() == null ? other.getMenuname() == null : this.getMenuname().equals(other.getMenuname()))
            && (this.getMenuurl() == null ? other.getMenuurl() == null : this.getMenuurl().equals(other.getMenuurl()))
            && (this.getParentid() == null ? other.getParentid() == null : this.getParentid().equals(other.getParentid()))
            && (this.getMenuorder() == null ? other.getMenuorder() == null : this.getMenuorder().equals(other.getMenuorder()))
            && (this.getMenuicon() == null ? other.getMenuicon() == null : this.getMenuicon().equals(other.getMenuicon()))
            && (this.getMenutype() == null ? other.getMenutype() == null : this.getMenutype().equals(other.getMenutype()))
            && (this.getMenustate() == null ? other.getMenustate() == null : this.getMenustate().equals(other.getMenustate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_MENU
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMenuid() == null) ? 0 : getMenuid().hashCode());
        result = prime * result + ((getMenuname() == null) ? 0 : getMenuname().hashCode());
        result = prime * result + ((getMenuurl() == null) ? 0 : getMenuurl().hashCode());
        result = prime * result + ((getParentid() == null) ? 0 : getParentid().hashCode());
        result = prime * result + ((getMenuorder() == null) ? 0 : getMenuorder().hashCode());
        result = prime * result + ((getMenuicon() == null) ? 0 : getMenuicon().hashCode());
        result = prime * result + ((getMenutype() == null) ? 0 : getMenutype().hashCode());
        result = prime * result + ((getMenustate() == null) ? 0 : getMenustate().hashCode());
        return result;
    }
}