package org.boot.facede.privilege.model;

import java.util.ArrayList;
import java.util.List;

public class RoleCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    public RoleCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoleidIsNull() {
            addCriterion("ROLEID is null");
            return (Criteria) this;
        }

        public Criteria andRoleidIsNotNull() {
            addCriterion("ROLEID is not null");
            return (Criteria) this;
        }

        public Criteria andRoleidEqualTo(String value) {
            addCriterion("ROLEID =", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotEqualTo(String value) {
            addCriterion("ROLEID <>", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidGreaterThan(String value) {
            addCriterion("ROLEID >", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidGreaterThanOrEqualTo(String value) {
            addCriterion("ROLEID >=", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLessThan(String value) {
            addCriterion("ROLEID <", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLessThanOrEqualTo(String value) {
            addCriterion("ROLEID <=", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLike(String value) {
            addCriterion("ROLEID like", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotLike(String value) {
            addCriterion("ROLEID not like", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidIn(List<String> values) {
            addCriterion("ROLEID in", values, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotIn(List<String> values) {
            addCriterion("ROLEID not in", values, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidBetween(String value1, String value2) {
            addCriterion("ROLEID between", value1, value2, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotBetween(String value1, String value2) {
            addCriterion("ROLEID not between", value1, value2, "roleid");
            return (Criteria) this;
        }

        public Criteria andRolenameIsNull() {
            addCriterion("ROLENAME is null");
            return (Criteria) this;
        }

        public Criteria andRolenameIsNotNull() {
            addCriterion("ROLENAME is not null");
            return (Criteria) this;
        }

        public Criteria andRolenameEqualTo(String value) {
            addCriterion("ROLENAME =", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotEqualTo(String value) {
            addCriterion("ROLENAME <>", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameGreaterThan(String value) {
            addCriterion("ROLENAME >", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameGreaterThanOrEqualTo(String value) {
            addCriterion("ROLENAME >=", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameLessThan(String value) {
            addCriterion("ROLENAME <", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameLessThanOrEqualTo(String value) {
            addCriterion("ROLENAME <=", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameLike(String value) {
            addCriterion("ROLENAME like", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotLike(String value) {
            addCriterion("ROLENAME not like", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameIn(List<String> values) {
            addCriterion("ROLENAME in", values, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotIn(List<String> values) {
            addCriterion("ROLENAME not in", values, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameBetween(String value1, String value2) {
            addCriterion("ROLENAME between", value1, value2, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotBetween(String value1, String value2) {
            addCriterion("ROLENAME not between", value1, value2, "rolename");
            return (Criteria) this;
        }

        public Criteria andRightsIsNull() {
            addCriterion("RIGHTS is null");
            return (Criteria) this;
        }

        public Criteria andRightsIsNotNull() {
            addCriterion("RIGHTS is not null");
            return (Criteria) this;
        }

        public Criteria andRightsEqualTo(String value) {
            addCriterion("RIGHTS =", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsNotEqualTo(String value) {
            addCriterion("RIGHTS <>", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsGreaterThan(String value) {
            addCriterion("RIGHTS >", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsGreaterThanOrEqualTo(String value) {
            addCriterion("RIGHTS >=", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsLessThan(String value) {
            addCriterion("RIGHTS <", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsLessThanOrEqualTo(String value) {
            addCriterion("RIGHTS <=", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsLike(String value) {
            addCriterion("RIGHTS like", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsNotLike(String value) {
            addCriterion("RIGHTS not like", value, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsIn(List<String> values) {
            addCriterion("RIGHTS in", values, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsNotIn(List<String> values) {
            addCriterion("RIGHTS not in", values, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsBetween(String value1, String value2) {
            addCriterion("RIGHTS between", value1, value2, "rights");
            return (Criteria) this;
        }

        public Criteria andRightsNotBetween(String value1, String value2) {
            addCriterion("RIGHTS not between", value1, value2, "rights");
            return (Criteria) this;
        }

        public Criteria andParentidIsNull() {
            addCriterion("PARENTID is null");
            return (Criteria) this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("PARENTID is not null");
            return (Criteria) this;
        }

        public Criteria andParentidEqualTo(String value) {
            addCriterion("PARENTID =", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotEqualTo(String value) {
            addCriterion("PARENTID <>", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThan(String value) {
            addCriterion("PARENTID >", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(String value) {
            addCriterion("PARENTID >=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThan(String value) {
            addCriterion("PARENTID <", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThanOrEqualTo(String value) {
            addCriterion("PARENTID <=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLike(String value) {
            addCriterion("PARENTID like", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotLike(String value) {
            addCriterion("PARENTID not like", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidIn(List<String> values) {
            addCriterion("PARENTID in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotIn(List<String> values) {
            addCriterion("PARENTID not in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidBetween(String value1, String value2) {
            addCriterion("PARENTID between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotBetween(String value1, String value2) {
            addCriterion("PARENTID not between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andAddqxIsNull() {
            addCriterion("ADDQX is null");
            return (Criteria) this;
        }

        public Criteria andAddqxIsNotNull() {
            addCriterion("ADDQX is not null");
            return (Criteria) this;
        }

        public Criteria andAddqxEqualTo(String value) {
            addCriterion("ADDQX =", value, "addqx");
            return (Criteria) this;
        }

        public Criteria andAddqxNotEqualTo(String value) {
            addCriterion("ADDQX <>", value, "addqx");
            return (Criteria) this;
        }

        public Criteria andAddqxGreaterThan(String value) {
            addCriterion("ADDQX >", value, "addqx");
            return (Criteria) this;
        }

        public Criteria andAddqxGreaterThanOrEqualTo(String value) {
            addCriterion("ADDQX >=", value, "addqx");
            return (Criteria) this;
        }

        public Criteria andAddqxLessThan(String value) {
            addCriterion("ADDQX <", value, "addqx");
            return (Criteria) this;
        }

        public Criteria andAddqxLessThanOrEqualTo(String value) {
            addCriterion("ADDQX <=", value, "addqx");
            return (Criteria) this;
        }

        public Criteria andAddqxLike(String value) {
            addCriterion("ADDQX like", value, "addqx");
            return (Criteria) this;
        }

        public Criteria andAddqxNotLike(String value) {
            addCriterion("ADDQX not like", value, "addqx");
            return (Criteria) this;
        }

        public Criteria andAddqxIn(List<String> values) {
            addCriterion("ADDQX in", values, "addqx");
            return (Criteria) this;
        }

        public Criteria andAddqxNotIn(List<String> values) {
            addCriterion("ADDQX not in", values, "addqx");
            return (Criteria) this;
        }

        public Criteria andAddqxBetween(String value1, String value2) {
            addCriterion("ADDQX between", value1, value2, "addqx");
            return (Criteria) this;
        }

        public Criteria andAddqxNotBetween(String value1, String value2) {
            addCriterion("ADDQX not between", value1, value2, "addqx");
            return (Criteria) this;
        }

        public Criteria andDelqxIsNull() {
            addCriterion("DELQX is null");
            return (Criteria) this;
        }

        public Criteria andDelqxIsNotNull() {
            addCriterion("DELQX is not null");
            return (Criteria) this;
        }

        public Criteria andDelqxEqualTo(String value) {
            addCriterion("DELQX =", value, "delqx");
            return (Criteria) this;
        }

        public Criteria andDelqxNotEqualTo(String value) {
            addCriterion("DELQX <>", value, "delqx");
            return (Criteria) this;
        }

        public Criteria andDelqxGreaterThan(String value) {
            addCriterion("DELQX >", value, "delqx");
            return (Criteria) this;
        }

        public Criteria andDelqxGreaterThanOrEqualTo(String value) {
            addCriterion("DELQX >=", value, "delqx");
            return (Criteria) this;
        }

        public Criteria andDelqxLessThan(String value) {
            addCriterion("DELQX <", value, "delqx");
            return (Criteria) this;
        }

        public Criteria andDelqxLessThanOrEqualTo(String value) {
            addCriterion("DELQX <=", value, "delqx");
            return (Criteria) this;
        }

        public Criteria andDelqxLike(String value) {
            addCriterion("DELQX like", value, "delqx");
            return (Criteria) this;
        }

        public Criteria andDelqxNotLike(String value) {
            addCriterion("DELQX not like", value, "delqx");
            return (Criteria) this;
        }

        public Criteria andDelqxIn(List<String> values) {
            addCriterion("DELQX in", values, "delqx");
            return (Criteria) this;
        }

        public Criteria andDelqxNotIn(List<String> values) {
            addCriterion("DELQX not in", values, "delqx");
            return (Criteria) this;
        }

        public Criteria andDelqxBetween(String value1, String value2) {
            addCriterion("DELQX between", value1, value2, "delqx");
            return (Criteria) this;
        }

        public Criteria andDelqxNotBetween(String value1, String value2) {
            addCriterion("DELQX not between", value1, value2, "delqx");
            return (Criteria) this;
        }

        public Criteria andEditqxIsNull() {
            addCriterion("EDITQX is null");
            return (Criteria) this;
        }

        public Criteria andEditqxIsNotNull() {
            addCriterion("EDITQX is not null");
            return (Criteria) this;
        }

        public Criteria andEditqxEqualTo(String value) {
            addCriterion("EDITQX =", value, "editqx");
            return (Criteria) this;
        }

        public Criteria andEditqxNotEqualTo(String value) {
            addCriterion("EDITQX <>", value, "editqx");
            return (Criteria) this;
        }

        public Criteria andEditqxGreaterThan(String value) {
            addCriterion("EDITQX >", value, "editqx");
            return (Criteria) this;
        }

        public Criteria andEditqxGreaterThanOrEqualTo(String value) {
            addCriterion("EDITQX >=", value, "editqx");
            return (Criteria) this;
        }

        public Criteria andEditqxLessThan(String value) {
            addCriterion("EDITQX <", value, "editqx");
            return (Criteria) this;
        }

        public Criteria andEditqxLessThanOrEqualTo(String value) {
            addCriterion("EDITQX <=", value, "editqx");
            return (Criteria) this;
        }

        public Criteria andEditqxLike(String value) {
            addCriterion("EDITQX like", value, "editqx");
            return (Criteria) this;
        }

        public Criteria andEditqxNotLike(String value) {
            addCriterion("EDITQX not like", value, "editqx");
            return (Criteria) this;
        }

        public Criteria andEditqxIn(List<String> values) {
            addCriterion("EDITQX in", values, "editqx");
            return (Criteria) this;
        }

        public Criteria andEditqxNotIn(List<String> values) {
            addCriterion("EDITQX not in", values, "editqx");
            return (Criteria) this;
        }

        public Criteria andEditqxBetween(String value1, String value2) {
            addCriterion("EDITQX between", value1, value2, "editqx");
            return (Criteria) this;
        }

        public Criteria andEditqxNotBetween(String value1, String value2) {
            addCriterion("EDITQX not between", value1, value2, "editqx");
            return (Criteria) this;
        }

        public Criteria andChaqxIsNull() {
            addCriterion("CHAQX is null");
            return (Criteria) this;
        }

        public Criteria andChaqxIsNotNull() {
            addCriterion("CHAQX is not null");
            return (Criteria) this;
        }

        public Criteria andChaqxEqualTo(String value) {
            addCriterion("CHAQX =", value, "chaqx");
            return (Criteria) this;
        }

        public Criteria andChaqxNotEqualTo(String value) {
            addCriterion("CHAQX <>", value, "chaqx");
            return (Criteria) this;
        }

        public Criteria andChaqxGreaterThan(String value) {
            addCriterion("CHAQX >", value, "chaqx");
            return (Criteria) this;
        }

        public Criteria andChaqxGreaterThanOrEqualTo(String value) {
            addCriterion("CHAQX >=", value, "chaqx");
            return (Criteria) this;
        }

        public Criteria andChaqxLessThan(String value) {
            addCriterion("CHAQX <", value, "chaqx");
            return (Criteria) this;
        }

        public Criteria andChaqxLessThanOrEqualTo(String value) {
            addCriterion("CHAQX <=", value, "chaqx");
            return (Criteria) this;
        }

        public Criteria andChaqxLike(String value) {
            addCriterion("CHAQX like", value, "chaqx");
            return (Criteria) this;
        }

        public Criteria andChaqxNotLike(String value) {
            addCriterion("CHAQX not like", value, "chaqx");
            return (Criteria) this;
        }

        public Criteria andChaqxIn(List<String> values) {
            addCriterion("CHAQX in", values, "chaqx");
            return (Criteria) this;
        }

        public Criteria andChaqxNotIn(List<String> values) {
            addCriterion("CHAQX not in", values, "chaqx");
            return (Criteria) this;
        }

        public Criteria andChaqxBetween(String value1, String value2) {
            addCriterion("CHAQX between", value1, value2, "chaqx");
            return (Criteria) this;
        }

        public Criteria andChaqxNotBetween(String value1, String value2) {
            addCriterion("CHAQX not between", value1, value2, "chaqx");
            return (Criteria) this;
        }

        public Criteria andRoleidLikeInsensitive(String value) {
            addCriterion("upper(ROLEID) like", value.toUpperCase(), "roleid");
            return (Criteria) this;
        }

        public Criteria andRolenameLikeInsensitive(String value) {
            addCriterion("upper(ROLENAME) like", value.toUpperCase(), "rolename");
            return (Criteria) this;
        }

        public Criteria andRightsLikeInsensitive(String value) {
            addCriterion("upper(RIGHTS) like", value.toUpperCase(), "rights");
            return (Criteria) this;
        }

        public Criteria andParentidLikeInsensitive(String value) {
            addCriterion("upper(PARENTID) like", value.toUpperCase(), "parentid");
            return (Criteria) this;
        }

        public Criteria andAddqxLikeInsensitive(String value) {
            addCriterion("upper(ADDQX) like", value.toUpperCase(), "addqx");
            return (Criteria) this;
        }

        public Criteria andDelqxLikeInsensitive(String value) {
            addCriterion("upper(DELQX) like", value.toUpperCase(), "delqx");
            return (Criteria) this;
        }

        public Criteria andEditqxLikeInsensitive(String value) {
            addCriterion("upper(EDITQX) like", value.toUpperCase(), "editqx");
            return (Criteria) this;
        }

        public Criteria andChaqxLikeInsensitive(String value) {
            addCriterion("upper(CHAQX) like", value.toUpperCase(), "chaqx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}