package org.boot.facede.privilege.model;

import java.io.Serializable;

public class Role implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.ROLEID
     *
     * @mbggenerated
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.ROLENAME
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.RIGHTS
     *
     * @mbggenerated
     */
    private String rights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.PARENTID
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.ADDQX
     *
     * @mbggenerated
     */
    private String addqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.DELQX
     *
     * @mbggenerated
     */
    private String delqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.EDITQX
     *
     * @mbggenerated
     */
    private String editqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_ROLE.CHAQX
     *
     * @mbggenerated
     */
    private String chaqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.ROLEID
     *
     * @return the value of T_SYS_ROLE.ROLEID
     *
     * @mbggenerated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.ROLEID
     *
     * @param roleid the value for T_SYS_ROLE.ROLEID
     *
     * @mbggenerated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.ROLENAME
     *
     * @return the value of T_SYS_ROLE.ROLENAME
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.ROLENAME
     *
     * @param rolename the value for T_SYS_ROLE.ROLENAME
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.RIGHTS
     *
     * @return the value of T_SYS_ROLE.RIGHTS
     *
     * @mbggenerated
     */
    public String getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.RIGHTS
     *
     * @param rights the value for T_SYS_ROLE.RIGHTS
     *
     * @mbggenerated
     */
    public void setRights(String rights) {
        this.rights = rights == null ? null : rights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.PARENTID
     *
     * @return the value of T_SYS_ROLE.PARENTID
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.PARENTID
     *
     * @param parentid the value for T_SYS_ROLE.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.ADDQX
     *
     * @return the value of T_SYS_ROLE.ADDQX
     *
     * @mbggenerated
     */
    public String getAddqx() {
        return addqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.ADDQX
     *
     * @param addqx the value for T_SYS_ROLE.ADDQX
     *
     * @mbggenerated
     */
    public void setAddqx(String addqx) {
        this.addqx = addqx == null ? null : addqx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.DELQX
     *
     * @return the value of T_SYS_ROLE.DELQX
     *
     * @mbggenerated
     */
    public String getDelqx() {
        return delqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.DELQX
     *
     * @param delqx the value for T_SYS_ROLE.DELQX
     *
     * @mbggenerated
     */
    public void setDelqx(String delqx) {
        this.delqx = delqx == null ? null : delqx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.EDITQX
     *
     * @return the value of T_SYS_ROLE.EDITQX
     *
     * @mbggenerated
     */
    public String getEditqx() {
        return editqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.EDITQX
     *
     * @param editqx the value for T_SYS_ROLE.EDITQX
     *
     * @mbggenerated
     */
    public void setEditqx(String editqx) {
        this.editqx = editqx == null ? null : editqx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_ROLE.CHAQX
     *
     * @return the value of T_SYS_ROLE.CHAQX
     *
     * @mbggenerated
     */
    public String getChaqx() {
        return chaqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_ROLE.CHAQX
     *
     * @param chaqx the value for T_SYS_ROLE.CHAQX
     *
     * @mbggenerated
     */
    public void setChaqx(String chaqx) {
        this.chaqx = chaqx == null ? null : chaqx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", rolename=").append(rolename);
        sb.append(", rights=").append(rights);
        sb.append(", parentid=").append(parentid);
        sb.append(", addqx=").append(addqx);
        sb.append(", delqx=").append(delqx);
        sb.append(", editqx=").append(editqx);
        sb.append(", chaqx=").append(chaqx);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Role other = (Role) that;
        return (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getRolename() == null ? other.getRolename() == null : this.getRolename().equals(other.getRolename()))
            && (this.getRights() == null ? other.getRights() == null : this.getRights().equals(other.getRights()))
            && (this.getParentid() == null ? other.getParentid() == null : this.getParentid().equals(other.getParentid()))
            && (this.getAddqx() == null ? other.getAddqx() == null : this.getAddqx().equals(other.getAddqx()))
            && (this.getDelqx() == null ? other.getDelqx() == null : this.getDelqx().equals(other.getDelqx()))
            && (this.getEditqx() == null ? other.getEditqx() == null : this.getEditqx().equals(other.getEditqx()))
            && (this.getChaqx() == null ? other.getChaqx() == null : this.getChaqx().equals(other.getChaqx()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getRolename() == null) ? 0 : getRolename().hashCode());
        result = prime * result + ((getRights() == null) ? 0 : getRights().hashCode());
        result = prime * result + ((getParentid() == null) ? 0 : getParentid().hashCode());
        result = prime * result + ((getAddqx() == null) ? 0 : getAddqx().hashCode());
        result = prime * result + ((getDelqx() == null) ? 0 : getDelqx().hashCode());
        result = prime * result + ((getEditqx() == null) ? 0 : getEditqx().hashCode());
        result = prime * result + ((getChaqx() == null) ? 0 : getChaqx().hashCode());
        return result;
    }
}