package org.boot.facede.privilege.model;

import java.util.ArrayList;
import java.util.List;

public class RoleButtonCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    public RoleButtonCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRbidIsNull() {
            addCriterion("RBID is null");
            return (Criteria) this;
        }

        public Criteria andRbidIsNotNull() {
            addCriterion("RBID is not null");
            return (Criteria) this;
        }

        public Criteria andRbidEqualTo(String value) {
            addCriterion("RBID =", value, "rbid");
            return (Criteria) this;
        }

        public Criteria andRbidNotEqualTo(String value) {
            addCriterion("RBID <>", value, "rbid");
            return (Criteria) this;
        }

        public Criteria andRbidGreaterThan(String value) {
            addCriterion("RBID >", value, "rbid");
            return (Criteria) this;
        }

        public Criteria andRbidGreaterThanOrEqualTo(String value) {
            addCriterion("RBID >=", value, "rbid");
            return (Criteria) this;
        }

        public Criteria andRbidLessThan(String value) {
            addCriterion("RBID <", value, "rbid");
            return (Criteria) this;
        }

        public Criteria andRbidLessThanOrEqualTo(String value) {
            addCriterion("RBID <=", value, "rbid");
            return (Criteria) this;
        }

        public Criteria andRbidLike(String value) {
            addCriterion("RBID like", value, "rbid");
            return (Criteria) this;
        }

        public Criteria andRbidNotLike(String value) {
            addCriterion("RBID not like", value, "rbid");
            return (Criteria) this;
        }

        public Criteria andRbidIn(List<String> values) {
            addCriterion("RBID in", values, "rbid");
            return (Criteria) this;
        }

        public Criteria andRbidNotIn(List<String> values) {
            addCriterion("RBID not in", values, "rbid");
            return (Criteria) this;
        }

        public Criteria andRbidBetween(String value1, String value2) {
            addCriterion("RBID between", value1, value2, "rbid");
            return (Criteria) this;
        }

        public Criteria andRbidNotBetween(String value1, String value2) {
            addCriterion("RBID not between", value1, value2, "rbid");
            return (Criteria) this;
        }

        public Criteria andRoleidIsNull() {
            addCriterion("ROLEID is null");
            return (Criteria) this;
        }

        public Criteria andRoleidIsNotNull() {
            addCriterion("ROLEID is not null");
            return (Criteria) this;
        }

        public Criteria andRoleidEqualTo(String value) {
            addCriterion("ROLEID =", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotEqualTo(String value) {
            addCriterion("ROLEID <>", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidGreaterThan(String value) {
            addCriterion("ROLEID >", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidGreaterThanOrEqualTo(String value) {
            addCriterion("ROLEID >=", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLessThan(String value) {
            addCriterion("ROLEID <", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLessThanOrEqualTo(String value) {
            addCriterion("ROLEID <=", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLike(String value) {
            addCriterion("ROLEID like", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotLike(String value) {
            addCriterion("ROLEID not like", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidIn(List<String> values) {
            addCriterion("ROLEID in", values, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotIn(List<String> values) {
            addCriterion("ROLEID not in", values, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidBetween(String value1, String value2) {
            addCriterion("ROLEID between", value1, value2, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotBetween(String value1, String value2) {
            addCriterion("ROLEID not between", value1, value2, "roleid");
            return (Criteria) this;
        }

        public Criteria andButtonidIsNull() {
            addCriterion("BUTTONID is null");
            return (Criteria) this;
        }

        public Criteria andButtonidIsNotNull() {
            addCriterion("BUTTONID is not null");
            return (Criteria) this;
        }

        public Criteria andButtonidEqualTo(String value) {
            addCriterion("BUTTONID =", value, "buttonid");
            return (Criteria) this;
        }

        public Criteria andButtonidNotEqualTo(String value) {
            addCriterion("BUTTONID <>", value, "buttonid");
            return (Criteria) this;
        }

        public Criteria andButtonidGreaterThan(String value) {
            addCriterion("BUTTONID >", value, "buttonid");
            return (Criteria) this;
        }

        public Criteria andButtonidGreaterThanOrEqualTo(String value) {
            addCriterion("BUTTONID >=", value, "buttonid");
            return (Criteria) this;
        }

        public Criteria andButtonidLessThan(String value) {
            addCriterion("BUTTONID <", value, "buttonid");
            return (Criteria) this;
        }

        public Criteria andButtonidLessThanOrEqualTo(String value) {
            addCriterion("BUTTONID <=", value, "buttonid");
            return (Criteria) this;
        }

        public Criteria andButtonidLike(String value) {
            addCriterion("BUTTONID like", value, "buttonid");
            return (Criteria) this;
        }

        public Criteria andButtonidNotLike(String value) {
            addCriterion("BUTTONID not like", value, "buttonid");
            return (Criteria) this;
        }

        public Criteria andButtonidIn(List<String> values) {
            addCriterion("BUTTONID in", values, "buttonid");
            return (Criteria) this;
        }

        public Criteria andButtonidNotIn(List<String> values) {
            addCriterion("BUTTONID not in", values, "buttonid");
            return (Criteria) this;
        }

        public Criteria andButtonidBetween(String value1, String value2) {
            addCriterion("BUTTONID between", value1, value2, "buttonid");
            return (Criteria) this;
        }

        public Criteria andButtonidNotBetween(String value1, String value2) {
            addCriterion("BUTTONID not between", value1, value2, "buttonid");
            return (Criteria) this;
        }

        public Criteria andRbidLikeInsensitive(String value) {
            addCriterion("upper(RBID) like", value.toUpperCase(), "rbid");
            return (Criteria) this;
        }

        public Criteria andRoleidLikeInsensitive(String value) {
            addCriterion("upper(ROLEID) like", value.toUpperCase(), "roleid");
            return (Criteria) this;
        }

        public Criteria andButtonidLikeInsensitive(String value) {
            addCriterion("upper(BUTTONID) like", value.toUpperCase(), "buttonid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}