package org.boot.facede.core.model;

import java.io.Serializable;
import java.util.Date;

public class Org implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.VC_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private String vcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.VC_CASCADE_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private String vcCascadeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.VC_NAME_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private String vcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.VC_HOTKEY_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private String vcHotkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.VC_PARENT_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private String vcParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.VC_IS_LEAF_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private String vcIsLeaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.VC_IS_AUTO_EXPAND_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private String vcIsAutoExpand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.VC_ICON_NAME_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private String vcIconName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.VC_TYPE_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private String vcType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.VC_BIZ_CODE_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private String vcBizCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.IN_SORT_NO_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private Integer inSortNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.VC_REMARK_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private String vcRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.VC_IS_DEL_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private String vcIsDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.DT_CREETE_TIME_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private Date dtCreeteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_org.VC_CREATE_BY_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    private String vcCreateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.VC_ID_
     *
     * @return the value of boot_org.VC_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public String getVcId() {
        return vcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.VC_ID_
     *
     * @param vcId the value for boot_org.VC_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setVcId(String vcId) {
        this.vcId = vcId == null ? null : vcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.VC_CASCADE_ID_
     *
     * @return the value of boot_org.VC_CASCADE_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public String getVcCascadeId() {
        return vcCascadeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.VC_CASCADE_ID_
     *
     * @param vcCascadeId the value for boot_org.VC_CASCADE_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setVcCascadeId(String vcCascadeId) {
        this.vcCascadeId = vcCascadeId == null ? null : vcCascadeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.VC_NAME_
     *
     * @return the value of boot_org.VC_NAME_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public String getVcName() {
        return vcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.VC_NAME_
     *
     * @param vcName the value for boot_org.VC_NAME_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setVcName(String vcName) {
        this.vcName = vcName == null ? null : vcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.VC_HOTKEY_
     *
     * @return the value of boot_org.VC_HOTKEY_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public String getVcHotkey() {
        return vcHotkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.VC_HOTKEY_
     *
     * @param vcHotkey the value for boot_org.VC_HOTKEY_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setVcHotkey(String vcHotkey) {
        this.vcHotkey = vcHotkey == null ? null : vcHotkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.VC_PARENT_ID_
     *
     * @return the value of boot_org.VC_PARENT_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public String getVcParentId() {
        return vcParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.VC_PARENT_ID_
     *
     * @param vcParentId the value for boot_org.VC_PARENT_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setVcParentId(String vcParentId) {
        this.vcParentId = vcParentId == null ? null : vcParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.VC_IS_LEAF_
     *
     * @return the value of boot_org.VC_IS_LEAF_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public String getVcIsLeaf() {
        return vcIsLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.VC_IS_LEAF_
     *
     * @param vcIsLeaf the value for boot_org.VC_IS_LEAF_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setVcIsLeaf(String vcIsLeaf) {
        this.vcIsLeaf = vcIsLeaf == null ? null : vcIsLeaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.VC_IS_AUTO_EXPAND_
     *
     * @return the value of boot_org.VC_IS_AUTO_EXPAND_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public String getVcIsAutoExpand() {
        return vcIsAutoExpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.VC_IS_AUTO_EXPAND_
     *
     * @param vcIsAutoExpand the value for boot_org.VC_IS_AUTO_EXPAND_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setVcIsAutoExpand(String vcIsAutoExpand) {
        this.vcIsAutoExpand = vcIsAutoExpand == null ? null : vcIsAutoExpand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.VC_ICON_NAME_
     *
     * @return the value of boot_org.VC_ICON_NAME_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public String getVcIconName() {
        return vcIconName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.VC_ICON_NAME_
     *
     * @param vcIconName the value for boot_org.VC_ICON_NAME_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setVcIconName(String vcIconName) {
        this.vcIconName = vcIconName == null ? null : vcIconName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.VC_TYPE_
     *
     * @return the value of boot_org.VC_TYPE_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public String getVcType() {
        return vcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.VC_TYPE_
     *
     * @param vcType the value for boot_org.VC_TYPE_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setVcType(String vcType) {
        this.vcType = vcType == null ? null : vcType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.VC_BIZ_CODE_
     *
     * @return the value of boot_org.VC_BIZ_CODE_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public String getVcBizCode() {
        return vcBizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.VC_BIZ_CODE_
     *
     * @param vcBizCode the value for boot_org.VC_BIZ_CODE_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setVcBizCode(String vcBizCode) {
        this.vcBizCode = vcBizCode == null ? null : vcBizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.IN_SORT_NO_
     *
     * @return the value of boot_org.IN_SORT_NO_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public Integer getInSortNo() {
        return inSortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.IN_SORT_NO_
     *
     * @param inSortNo the value for boot_org.IN_SORT_NO_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setInSortNo(Integer inSortNo) {
        this.inSortNo = inSortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.VC_REMARK_
     *
     * @return the value of boot_org.VC_REMARK_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public String getVcRemark() {
        return vcRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.VC_REMARK_
     *
     * @param vcRemark the value for boot_org.VC_REMARK_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setVcRemark(String vcRemark) {
        this.vcRemark = vcRemark == null ? null : vcRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.VC_IS_DEL_
     *
     * @return the value of boot_org.VC_IS_DEL_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public String getVcIsDel() {
        return vcIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.VC_IS_DEL_
     *
     * @param vcIsDel the value for boot_org.VC_IS_DEL_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setVcIsDel(String vcIsDel) {
        this.vcIsDel = vcIsDel == null ? null : vcIsDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.DT_CREETE_TIME_
     *
     * @return the value of boot_org.DT_CREETE_TIME_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public Date getDtCreeteTime() {
        return dtCreeteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.DT_CREETE_TIME_
     *
     * @param dtCreeteTime the value for boot_org.DT_CREETE_TIME_
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setDtCreeteTime(Date dtCreeteTime) {
        this.dtCreeteTime = dtCreeteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_org.VC_CREATE_BY_
     *
     * @return the value of boot_org.VC_CREATE_BY_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcCreateBy() {
        return vcCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_org.VC_CREATE_BY_
     *
     * @param vcCreateBy the value for boot_org.VC_CREATE_BY_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcCreateBy(String vcCreateBy) {
        this.vcCreateBy = vcCreateBy == null ? null : vcCreateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vcId=").append(vcId);
        sb.append(", vcCascadeId=").append(vcCascadeId);
        sb.append(", vcName=").append(vcName);
        sb.append(", vcHotkey=").append(vcHotkey);
        sb.append(", vcParentId=").append(vcParentId);
        sb.append(", vcIsLeaf=").append(vcIsLeaf);
        sb.append(", vcIsAutoExpand=").append(vcIsAutoExpand);
        sb.append(", vcIconName=").append(vcIconName);
        sb.append(", vcType=").append(vcType);
        sb.append(", vcBizCode=").append(vcBizCode);
        sb.append(", inSortNo=").append(inSortNo);
        sb.append(", vcRemark=").append(vcRemark);
        sb.append(", vcIsDel=").append(vcIsDel);
        sb.append(", dtCreeteTime=").append(dtCreeteTime);
        sb.append(", vcCreateBy=").append(vcCreateBy);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Org other = (Org) that;
        return (this.getVcId() == null ? other.getVcId() == null : this.getVcId().equals(other.getVcId()))
            && (this.getVcCascadeId() == null ? other.getVcCascadeId() == null : this.getVcCascadeId().equals(other.getVcCascadeId()))
            && (this.getVcName() == null ? other.getVcName() == null : this.getVcName().equals(other.getVcName()))
            && (this.getVcHotkey() == null ? other.getVcHotkey() == null : this.getVcHotkey().equals(other.getVcHotkey()))
            && (this.getVcParentId() == null ? other.getVcParentId() == null : this.getVcParentId().equals(other.getVcParentId()))
            && (this.getVcIsLeaf() == null ? other.getVcIsLeaf() == null : this.getVcIsLeaf().equals(other.getVcIsLeaf()))
            && (this.getVcIsAutoExpand() == null ? other.getVcIsAutoExpand() == null : this.getVcIsAutoExpand().equals(other.getVcIsAutoExpand()))
            && (this.getVcIconName() == null ? other.getVcIconName() == null : this.getVcIconName().equals(other.getVcIconName()))
            && (this.getVcType() == null ? other.getVcType() == null : this.getVcType().equals(other.getVcType()))
            && (this.getVcBizCode() == null ? other.getVcBizCode() == null : this.getVcBizCode().equals(other.getVcBizCode()))
            && (this.getInSortNo() == null ? other.getInSortNo() == null : this.getInSortNo().equals(other.getInSortNo()))
            && (this.getVcRemark() == null ? other.getVcRemark() == null : this.getVcRemark().equals(other.getVcRemark()))
            && (this.getVcIsDel() == null ? other.getVcIsDel() == null : this.getVcIsDel().equals(other.getVcIsDel()))
            && (this.getDtCreeteTime() == null ? other.getDtCreeteTime() == null : this.getDtCreeteTime().equals(other.getDtCreeteTime()))
            && (this.getVcCreateBy() == null ? other.getVcCreateBy() == null : this.getVcCreateBy().equals(other.getVcCreateBy()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getVcId() == null) ? 0 : getVcId().hashCode());
        result = prime * result + ((getVcCascadeId() == null) ? 0 : getVcCascadeId().hashCode());
        result = prime * result + ((getVcName() == null) ? 0 : getVcName().hashCode());
        result = prime * result + ((getVcHotkey() == null) ? 0 : getVcHotkey().hashCode());
        result = prime * result + ((getVcParentId() == null) ? 0 : getVcParentId().hashCode());
        result = prime * result + ((getVcIsLeaf() == null) ? 0 : getVcIsLeaf().hashCode());
        result = prime * result + ((getVcIsAutoExpand() == null) ? 0 : getVcIsAutoExpand().hashCode());
        result = prime * result + ((getVcIconName() == null) ? 0 : getVcIconName().hashCode());
        result = prime * result + ((getVcType() == null) ? 0 : getVcType().hashCode());
        result = prime * result + ((getVcBizCode() == null) ? 0 : getVcBizCode().hashCode());
        result = prime * result + ((getInSortNo() == null) ? 0 : getInSortNo().hashCode());
        result = prime * result + ((getVcRemark() == null) ? 0 : getVcRemark().hashCode());
        result = prime * result + ((getVcIsDel() == null) ? 0 : getVcIsDel().hashCode());
        result = prime * result + ((getDtCreeteTime() == null) ? 0 : getDtCreeteTime().hashCode());
        result = prime * result + ((getVcCreateBy() == null) ? 0 : getVcCreateBy().hashCode());
        return result;
    }
}