package org.boot.facede.core.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrgCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public OrgCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVcIdIsNull() {
            addCriterion("VC_ID_ is null");
            return (Criteria) this;
        }

        public Criteria andVcIdIsNotNull() {
            addCriterion("VC_ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcIdEqualTo(String value) {
            addCriterion("VC_ID_ =", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdNotEqualTo(String value) {
            addCriterion("VC_ID_ <>", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdGreaterThan(String value) {
            addCriterion("VC_ID_ >", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdGreaterThanOrEqualTo(String value) {
            addCriterion("VC_ID_ >=", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdLessThan(String value) {
            addCriterion("VC_ID_ <", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdLessThanOrEqualTo(String value) {
            addCriterion("VC_ID_ <=", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdLike(String value) {
            addCriterion("VC_ID_ like", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdNotLike(String value) {
            addCriterion("VC_ID_ not like", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdIn(List<String> values) {
            addCriterion("VC_ID_ in", values, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdNotIn(List<String> values) {
            addCriterion("VC_ID_ not in", values, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdBetween(String value1, String value2) {
            addCriterion("VC_ID_ between", value1, value2, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdNotBetween(String value1, String value2) {
            addCriterion("VC_ID_ not between", value1, value2, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdIsNull() {
            addCriterion("VC_CASCADE_ID_ is null");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdIsNotNull() {
            addCriterion("VC_CASCADE_ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdEqualTo(String value) {
            addCriterion("VC_CASCADE_ID_ =", value, "vcCascadeId");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdNotEqualTo(String value) {
            addCriterion("VC_CASCADE_ID_ <>", value, "vcCascadeId");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdGreaterThan(String value) {
            addCriterion("VC_CASCADE_ID_ >", value, "vcCascadeId");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdGreaterThanOrEqualTo(String value) {
            addCriterion("VC_CASCADE_ID_ >=", value, "vcCascadeId");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdLessThan(String value) {
            addCriterion("VC_CASCADE_ID_ <", value, "vcCascadeId");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdLessThanOrEqualTo(String value) {
            addCriterion("VC_CASCADE_ID_ <=", value, "vcCascadeId");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdLike(String value) {
            addCriterion("VC_CASCADE_ID_ like", value, "vcCascadeId");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdNotLike(String value) {
            addCriterion("VC_CASCADE_ID_ not like", value, "vcCascadeId");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdIn(List<String> values) {
            addCriterion("VC_CASCADE_ID_ in", values, "vcCascadeId");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdNotIn(List<String> values) {
            addCriterion("VC_CASCADE_ID_ not in", values, "vcCascadeId");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdBetween(String value1, String value2) {
            addCriterion("VC_CASCADE_ID_ between", value1, value2, "vcCascadeId");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdNotBetween(String value1, String value2) {
            addCriterion("VC_CASCADE_ID_ not between", value1, value2, "vcCascadeId");
            return (Criteria) this;
        }

        public Criteria andVcNameIsNull() {
            addCriterion("VC_NAME_ is null");
            return (Criteria) this;
        }

        public Criteria andVcNameIsNotNull() {
            addCriterion("VC_NAME_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcNameEqualTo(String value) {
            addCriterion("VC_NAME_ =", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameNotEqualTo(String value) {
            addCriterion("VC_NAME_ <>", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameGreaterThan(String value) {
            addCriterion("VC_NAME_ >", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameGreaterThanOrEqualTo(String value) {
            addCriterion("VC_NAME_ >=", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameLessThan(String value) {
            addCriterion("VC_NAME_ <", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameLessThanOrEqualTo(String value) {
            addCriterion("VC_NAME_ <=", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameLike(String value) {
            addCriterion("VC_NAME_ like", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameNotLike(String value) {
            addCriterion("VC_NAME_ not like", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameIn(List<String> values) {
            addCriterion("VC_NAME_ in", values, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameNotIn(List<String> values) {
            addCriterion("VC_NAME_ not in", values, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameBetween(String value1, String value2) {
            addCriterion("VC_NAME_ between", value1, value2, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameNotBetween(String value1, String value2) {
            addCriterion("VC_NAME_ not between", value1, value2, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyIsNull() {
            addCriterion("VC_HOTKEY_ is null");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyIsNotNull() {
            addCriterion("VC_HOTKEY_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyEqualTo(String value) {
            addCriterion("VC_HOTKEY_ =", value, "vcHotkey");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyNotEqualTo(String value) {
            addCriterion("VC_HOTKEY_ <>", value, "vcHotkey");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyGreaterThan(String value) {
            addCriterion("VC_HOTKEY_ >", value, "vcHotkey");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyGreaterThanOrEqualTo(String value) {
            addCriterion("VC_HOTKEY_ >=", value, "vcHotkey");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyLessThan(String value) {
            addCriterion("VC_HOTKEY_ <", value, "vcHotkey");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyLessThanOrEqualTo(String value) {
            addCriterion("VC_HOTKEY_ <=", value, "vcHotkey");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyLike(String value) {
            addCriterion("VC_HOTKEY_ like", value, "vcHotkey");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyNotLike(String value) {
            addCriterion("VC_HOTKEY_ not like", value, "vcHotkey");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyIn(List<String> values) {
            addCriterion("VC_HOTKEY_ in", values, "vcHotkey");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyNotIn(List<String> values) {
            addCriterion("VC_HOTKEY_ not in", values, "vcHotkey");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyBetween(String value1, String value2) {
            addCriterion("VC_HOTKEY_ between", value1, value2, "vcHotkey");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyNotBetween(String value1, String value2) {
            addCriterion("VC_HOTKEY_ not between", value1, value2, "vcHotkey");
            return (Criteria) this;
        }

        public Criteria andVcParentIdIsNull() {
            addCriterion("VC_PARENT_ID_ is null");
            return (Criteria) this;
        }

        public Criteria andVcParentIdIsNotNull() {
            addCriterion("VC_PARENT_ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcParentIdEqualTo(String value) {
            addCriterion("VC_PARENT_ID_ =", value, "vcParentId");
            return (Criteria) this;
        }

        public Criteria andVcParentIdNotEqualTo(String value) {
            addCriterion("VC_PARENT_ID_ <>", value, "vcParentId");
            return (Criteria) this;
        }

        public Criteria andVcParentIdGreaterThan(String value) {
            addCriterion("VC_PARENT_ID_ >", value, "vcParentId");
            return (Criteria) this;
        }

        public Criteria andVcParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("VC_PARENT_ID_ >=", value, "vcParentId");
            return (Criteria) this;
        }

        public Criteria andVcParentIdLessThan(String value) {
            addCriterion("VC_PARENT_ID_ <", value, "vcParentId");
            return (Criteria) this;
        }

        public Criteria andVcParentIdLessThanOrEqualTo(String value) {
            addCriterion("VC_PARENT_ID_ <=", value, "vcParentId");
            return (Criteria) this;
        }

        public Criteria andVcParentIdLike(String value) {
            addCriterion("VC_PARENT_ID_ like", value, "vcParentId");
            return (Criteria) this;
        }

        public Criteria andVcParentIdNotLike(String value) {
            addCriterion("VC_PARENT_ID_ not like", value, "vcParentId");
            return (Criteria) this;
        }

        public Criteria andVcParentIdIn(List<String> values) {
            addCriterion("VC_PARENT_ID_ in", values, "vcParentId");
            return (Criteria) this;
        }

        public Criteria andVcParentIdNotIn(List<String> values) {
            addCriterion("VC_PARENT_ID_ not in", values, "vcParentId");
            return (Criteria) this;
        }

        public Criteria andVcParentIdBetween(String value1, String value2) {
            addCriterion("VC_PARENT_ID_ between", value1, value2, "vcParentId");
            return (Criteria) this;
        }

        public Criteria andVcParentIdNotBetween(String value1, String value2) {
            addCriterion("VC_PARENT_ID_ not between", value1, value2, "vcParentId");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafIsNull() {
            addCriterion("VC_IS_LEAF_ is null");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafIsNotNull() {
            addCriterion("VC_IS_LEAF_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafEqualTo(String value) {
            addCriterion("VC_IS_LEAF_ =", value, "vcIsLeaf");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafNotEqualTo(String value) {
            addCriterion("VC_IS_LEAF_ <>", value, "vcIsLeaf");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafGreaterThan(String value) {
            addCriterion("VC_IS_LEAF_ >", value, "vcIsLeaf");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafGreaterThanOrEqualTo(String value) {
            addCriterion("VC_IS_LEAF_ >=", value, "vcIsLeaf");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafLessThan(String value) {
            addCriterion("VC_IS_LEAF_ <", value, "vcIsLeaf");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafLessThanOrEqualTo(String value) {
            addCriterion("VC_IS_LEAF_ <=", value, "vcIsLeaf");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafLike(String value) {
            addCriterion("VC_IS_LEAF_ like", value, "vcIsLeaf");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafNotLike(String value) {
            addCriterion("VC_IS_LEAF_ not like", value, "vcIsLeaf");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafIn(List<String> values) {
            addCriterion("VC_IS_LEAF_ in", values, "vcIsLeaf");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafNotIn(List<String> values) {
            addCriterion("VC_IS_LEAF_ not in", values, "vcIsLeaf");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafBetween(String value1, String value2) {
            addCriterion("VC_IS_LEAF_ between", value1, value2, "vcIsLeaf");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafNotBetween(String value1, String value2) {
            addCriterion("VC_IS_LEAF_ not between", value1, value2, "vcIsLeaf");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandIsNull() {
            addCriterion("VC_IS_AUTO_EXPAND_ is null");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandIsNotNull() {
            addCriterion("VC_IS_AUTO_EXPAND_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandEqualTo(String value) {
            addCriterion("VC_IS_AUTO_EXPAND_ =", value, "vcIsAutoExpand");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandNotEqualTo(String value) {
            addCriterion("VC_IS_AUTO_EXPAND_ <>", value, "vcIsAutoExpand");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandGreaterThan(String value) {
            addCriterion("VC_IS_AUTO_EXPAND_ >", value, "vcIsAutoExpand");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandGreaterThanOrEqualTo(String value) {
            addCriterion("VC_IS_AUTO_EXPAND_ >=", value, "vcIsAutoExpand");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandLessThan(String value) {
            addCriterion("VC_IS_AUTO_EXPAND_ <", value, "vcIsAutoExpand");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandLessThanOrEqualTo(String value) {
            addCriterion("VC_IS_AUTO_EXPAND_ <=", value, "vcIsAutoExpand");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandLike(String value) {
            addCriterion("VC_IS_AUTO_EXPAND_ like", value, "vcIsAutoExpand");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandNotLike(String value) {
            addCriterion("VC_IS_AUTO_EXPAND_ not like", value, "vcIsAutoExpand");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandIn(List<String> values) {
            addCriterion("VC_IS_AUTO_EXPAND_ in", values, "vcIsAutoExpand");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandNotIn(List<String> values) {
            addCriterion("VC_IS_AUTO_EXPAND_ not in", values, "vcIsAutoExpand");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandBetween(String value1, String value2) {
            addCriterion("VC_IS_AUTO_EXPAND_ between", value1, value2, "vcIsAutoExpand");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandNotBetween(String value1, String value2) {
            addCriterion("VC_IS_AUTO_EXPAND_ not between", value1, value2, "vcIsAutoExpand");
            return (Criteria) this;
        }

        public Criteria andVcIconNameIsNull() {
            addCriterion("VC_ICON_NAME_ is null");
            return (Criteria) this;
        }

        public Criteria andVcIconNameIsNotNull() {
            addCriterion("VC_ICON_NAME_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcIconNameEqualTo(String value) {
            addCriterion("VC_ICON_NAME_ =", value, "vcIconName");
            return (Criteria) this;
        }

        public Criteria andVcIconNameNotEqualTo(String value) {
            addCriterion("VC_ICON_NAME_ <>", value, "vcIconName");
            return (Criteria) this;
        }

        public Criteria andVcIconNameGreaterThan(String value) {
            addCriterion("VC_ICON_NAME_ >", value, "vcIconName");
            return (Criteria) this;
        }

        public Criteria andVcIconNameGreaterThanOrEqualTo(String value) {
            addCriterion("VC_ICON_NAME_ >=", value, "vcIconName");
            return (Criteria) this;
        }

        public Criteria andVcIconNameLessThan(String value) {
            addCriterion("VC_ICON_NAME_ <", value, "vcIconName");
            return (Criteria) this;
        }

        public Criteria andVcIconNameLessThanOrEqualTo(String value) {
            addCriterion("VC_ICON_NAME_ <=", value, "vcIconName");
            return (Criteria) this;
        }

        public Criteria andVcIconNameLike(String value) {
            addCriterion("VC_ICON_NAME_ like", value, "vcIconName");
            return (Criteria) this;
        }

        public Criteria andVcIconNameNotLike(String value) {
            addCriterion("VC_ICON_NAME_ not like", value, "vcIconName");
            return (Criteria) this;
        }

        public Criteria andVcIconNameIn(List<String> values) {
            addCriterion("VC_ICON_NAME_ in", values, "vcIconName");
            return (Criteria) this;
        }

        public Criteria andVcIconNameNotIn(List<String> values) {
            addCriterion("VC_ICON_NAME_ not in", values, "vcIconName");
            return (Criteria) this;
        }

        public Criteria andVcIconNameBetween(String value1, String value2) {
            addCriterion("VC_ICON_NAME_ between", value1, value2, "vcIconName");
            return (Criteria) this;
        }

        public Criteria andVcIconNameNotBetween(String value1, String value2) {
            addCriterion("VC_ICON_NAME_ not between", value1, value2, "vcIconName");
            return (Criteria) this;
        }

        public Criteria andVcTypeIsNull() {
            addCriterion("VC_TYPE_ is null");
            return (Criteria) this;
        }

        public Criteria andVcTypeIsNotNull() {
            addCriterion("VC_TYPE_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcTypeEqualTo(String value) {
            addCriterion("VC_TYPE_ =", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeNotEqualTo(String value) {
            addCriterion("VC_TYPE_ <>", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeGreaterThan(String value) {
            addCriterion("VC_TYPE_ >", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeGreaterThanOrEqualTo(String value) {
            addCriterion("VC_TYPE_ >=", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeLessThan(String value) {
            addCriterion("VC_TYPE_ <", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeLessThanOrEqualTo(String value) {
            addCriterion("VC_TYPE_ <=", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeLike(String value) {
            addCriterion("VC_TYPE_ like", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeNotLike(String value) {
            addCriterion("VC_TYPE_ not like", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeIn(List<String> values) {
            addCriterion("VC_TYPE_ in", values, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeNotIn(List<String> values) {
            addCriterion("VC_TYPE_ not in", values, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeBetween(String value1, String value2) {
            addCriterion("VC_TYPE_ between", value1, value2, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeNotBetween(String value1, String value2) {
            addCriterion("VC_TYPE_ not between", value1, value2, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeIsNull() {
            addCriterion("VC_BIZ_CODE_ is null");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeIsNotNull() {
            addCriterion("VC_BIZ_CODE_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeEqualTo(String value) {
            addCriterion("VC_BIZ_CODE_ =", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeNotEqualTo(String value) {
            addCriterion("VC_BIZ_CODE_ <>", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeGreaterThan(String value) {
            addCriterion("VC_BIZ_CODE_ >", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeGreaterThanOrEqualTo(String value) {
            addCriterion("VC_BIZ_CODE_ >=", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeLessThan(String value) {
            addCriterion("VC_BIZ_CODE_ <", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeLessThanOrEqualTo(String value) {
            addCriterion("VC_BIZ_CODE_ <=", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeLike(String value) {
            addCriterion("VC_BIZ_CODE_ like", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeNotLike(String value) {
            addCriterion("VC_BIZ_CODE_ not like", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeIn(List<String> values) {
            addCriterion("VC_BIZ_CODE_ in", values, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeNotIn(List<String> values) {
            addCriterion("VC_BIZ_CODE_ not in", values, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeBetween(String value1, String value2) {
            addCriterion("VC_BIZ_CODE_ between", value1, value2, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeNotBetween(String value1, String value2) {
            addCriterion("VC_BIZ_CODE_ not between", value1, value2, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andInSortNoIsNull() {
            addCriterion("IN_SORT_NO_ is null");
            return (Criteria) this;
        }

        public Criteria andInSortNoIsNotNull() {
            addCriterion("IN_SORT_NO_ is not null");
            return (Criteria) this;
        }

        public Criteria andInSortNoEqualTo(Integer value) {
            addCriterion("IN_SORT_NO_ =", value, "inSortNo");
            return (Criteria) this;
        }

        public Criteria andInSortNoNotEqualTo(Integer value) {
            addCriterion("IN_SORT_NO_ <>", value, "inSortNo");
            return (Criteria) this;
        }

        public Criteria andInSortNoGreaterThan(Integer value) {
            addCriterion("IN_SORT_NO_ >", value, "inSortNo");
            return (Criteria) this;
        }

        public Criteria andInSortNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("IN_SORT_NO_ >=", value, "inSortNo");
            return (Criteria) this;
        }

        public Criteria andInSortNoLessThan(Integer value) {
            addCriterion("IN_SORT_NO_ <", value, "inSortNo");
            return (Criteria) this;
        }

        public Criteria andInSortNoLessThanOrEqualTo(Integer value) {
            addCriterion("IN_SORT_NO_ <=", value, "inSortNo");
            return (Criteria) this;
        }

        public Criteria andInSortNoIn(List<Integer> values) {
            addCriterion("IN_SORT_NO_ in", values, "inSortNo");
            return (Criteria) this;
        }

        public Criteria andInSortNoNotIn(List<Integer> values) {
            addCriterion("IN_SORT_NO_ not in", values, "inSortNo");
            return (Criteria) this;
        }

        public Criteria andInSortNoBetween(Integer value1, Integer value2) {
            addCriterion("IN_SORT_NO_ between", value1, value2, "inSortNo");
            return (Criteria) this;
        }

        public Criteria andInSortNoNotBetween(Integer value1, Integer value2) {
            addCriterion("IN_SORT_NO_ not between", value1, value2, "inSortNo");
            return (Criteria) this;
        }

        public Criteria andVcRemarkIsNull() {
            addCriterion("VC_REMARK_ is null");
            return (Criteria) this;
        }

        public Criteria andVcRemarkIsNotNull() {
            addCriterion("VC_REMARK_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcRemarkEqualTo(String value) {
            addCriterion("VC_REMARK_ =", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkNotEqualTo(String value) {
            addCriterion("VC_REMARK_ <>", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkGreaterThan(String value) {
            addCriterion("VC_REMARK_ >", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("VC_REMARK_ >=", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkLessThan(String value) {
            addCriterion("VC_REMARK_ <", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkLessThanOrEqualTo(String value) {
            addCriterion("VC_REMARK_ <=", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkLike(String value) {
            addCriterion("VC_REMARK_ like", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkNotLike(String value) {
            addCriterion("VC_REMARK_ not like", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkIn(List<String> values) {
            addCriterion("VC_REMARK_ in", values, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkNotIn(List<String> values) {
            addCriterion("VC_REMARK_ not in", values, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkBetween(String value1, String value2) {
            addCriterion("VC_REMARK_ between", value1, value2, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkNotBetween(String value1, String value2) {
            addCriterion("VC_REMARK_ not between", value1, value2, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcIsDelIsNull() {
            addCriterion("VC_IS_DEL_ is null");
            return (Criteria) this;
        }

        public Criteria andVcIsDelIsNotNull() {
            addCriterion("VC_IS_DEL_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcIsDelEqualTo(String value) {
            addCriterion("VC_IS_DEL_ =", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelNotEqualTo(String value) {
            addCriterion("VC_IS_DEL_ <>", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelGreaterThan(String value) {
            addCriterion("VC_IS_DEL_ >", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelGreaterThanOrEqualTo(String value) {
            addCriterion("VC_IS_DEL_ >=", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelLessThan(String value) {
            addCriterion("VC_IS_DEL_ <", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelLessThanOrEqualTo(String value) {
            addCriterion("VC_IS_DEL_ <=", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelLike(String value) {
            addCriterion("VC_IS_DEL_ like", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelNotLike(String value) {
            addCriterion("VC_IS_DEL_ not like", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelIn(List<String> values) {
            addCriterion("VC_IS_DEL_ in", values, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelNotIn(List<String> values) {
            addCriterion("VC_IS_DEL_ not in", values, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelBetween(String value1, String value2) {
            addCriterion("VC_IS_DEL_ between", value1, value2, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelNotBetween(String value1, String value2) {
            addCriterion("VC_IS_DEL_ not between", value1, value2, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andDtCreeteTimeIsNull() {
            addCriterion("DT_CREETE_TIME_ is null");
            return (Criteria) this;
        }

        public Criteria andDtCreeteTimeIsNotNull() {
            addCriterion("DT_CREETE_TIME_ is not null");
            return (Criteria) this;
        }

        public Criteria andDtCreeteTimeEqualTo(Date value) {
            addCriterion("DT_CREETE_TIME_ =", value, "dtCreeteTime");
            return (Criteria) this;
        }

        public Criteria andDtCreeteTimeNotEqualTo(Date value) {
            addCriterion("DT_CREETE_TIME_ <>", value, "dtCreeteTime");
            return (Criteria) this;
        }

        public Criteria andDtCreeteTimeGreaterThan(Date value) {
            addCriterion("DT_CREETE_TIME_ >", value, "dtCreeteTime");
            return (Criteria) this;
        }

        public Criteria andDtCreeteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DT_CREETE_TIME_ >=", value, "dtCreeteTime");
            return (Criteria) this;
        }

        public Criteria andDtCreeteTimeLessThan(Date value) {
            addCriterion("DT_CREETE_TIME_ <", value, "dtCreeteTime");
            return (Criteria) this;
        }

        public Criteria andDtCreeteTimeLessThanOrEqualTo(Date value) {
            addCriterion("DT_CREETE_TIME_ <=", value, "dtCreeteTime");
            return (Criteria) this;
        }

        public Criteria andDtCreeteTimeIn(List<Date> values) {
            addCriterion("DT_CREETE_TIME_ in", values, "dtCreeteTime");
            return (Criteria) this;
        }

        public Criteria andDtCreeteTimeNotIn(List<Date> values) {
            addCriterion("DT_CREETE_TIME_ not in", values, "dtCreeteTime");
            return (Criteria) this;
        }

        public Criteria andDtCreeteTimeBetween(Date value1, Date value2) {
            addCriterion("DT_CREETE_TIME_ between", value1, value2, "dtCreeteTime");
            return (Criteria) this;
        }

        public Criteria andDtCreeteTimeNotBetween(Date value1, Date value2) {
            addCriterion("DT_CREETE_TIME_ not between", value1, value2, "dtCreeteTime");
            return (Criteria) this;
        }

        public Criteria andVcCreateByIsNull() {
            addCriterion("VC_CREATE_BY_ is null");
            return (Criteria) this;
        }

        public Criteria andVcCreateByIsNotNull() {
            addCriterion("VC_CREATE_BY_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcCreateByEqualTo(String value) {
            addCriterion("VC_CREATE_BY_ =", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByNotEqualTo(String value) {
            addCriterion("VC_CREATE_BY_ <>", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByGreaterThan(String value) {
            addCriterion("VC_CREATE_BY_ >", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("VC_CREATE_BY_ >=", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByLessThan(String value) {
            addCriterion("VC_CREATE_BY_ <", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByLessThanOrEqualTo(String value) {
            addCriterion("VC_CREATE_BY_ <=", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByLike(String value) {
            addCriterion("VC_CREATE_BY_ like", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByNotLike(String value) {
            addCriterion("VC_CREATE_BY_ not like", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByIn(List<String> values) {
            addCriterion("VC_CREATE_BY_ in", values, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByNotIn(List<String> values) {
            addCriterion("VC_CREATE_BY_ not in", values, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByBetween(String value1, String value2) {
            addCriterion("VC_CREATE_BY_ between", value1, value2, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByNotBetween(String value1, String value2) {
            addCriterion("VC_CREATE_BY_ not between", value1, value2, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcIdLikeInsensitive(String value) {
            addCriterion("upper(VC_ID_) like", value.toUpperCase(), "vcId");
            return (Criteria) this;
        }

        public Criteria andVcCascadeIdLikeInsensitive(String value) {
            addCriterion("upper(VC_CASCADE_ID_) like", value.toUpperCase(), "vcCascadeId");
            return (Criteria) this;
        }

        public Criteria andVcNameLikeInsensitive(String value) {
            addCriterion("upper(VC_NAME_) like", value.toUpperCase(), "vcName");
            return (Criteria) this;
        }

        public Criteria andVcHotkeyLikeInsensitive(String value) {
            addCriterion("upper(VC_HOTKEY_) like", value.toUpperCase(), "vcHotkey");
            return (Criteria) this;
        }

        public Criteria andVcParentIdLikeInsensitive(String value) {
            addCriterion("upper(VC_PARENT_ID_) like", value.toUpperCase(), "vcParentId");
            return (Criteria) this;
        }

        public Criteria andVcIsLeafLikeInsensitive(String value) {
            addCriterion("upper(VC_IS_LEAF_) like", value.toUpperCase(), "vcIsLeaf");
            return (Criteria) this;
        }

        public Criteria andVcIsAutoExpandLikeInsensitive(String value) {
            addCriterion("upper(VC_IS_AUTO_EXPAND_) like", value.toUpperCase(), "vcIsAutoExpand");
            return (Criteria) this;
        }

        public Criteria andVcIconNameLikeInsensitive(String value) {
            addCriterion("upper(VC_ICON_NAME_) like", value.toUpperCase(), "vcIconName");
            return (Criteria) this;
        }

        public Criteria andVcTypeLikeInsensitive(String value) {
            addCriterion("upper(VC_TYPE_) like", value.toUpperCase(), "vcType");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeLikeInsensitive(String value) {
            addCriterion("upper(VC_BIZ_CODE_) like", value.toUpperCase(), "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcRemarkLikeInsensitive(String value) {
            addCriterion("upper(VC_REMARK_) like", value.toUpperCase(), "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcIsDelLikeInsensitive(String value) {
            addCriterion("upper(VC_IS_DEL_) like", value.toUpperCase(), "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcCreateByLikeInsensitive(String value) {
            addCriterion("upper(VC_CREATE_BY_) like", value.toUpperCase(), "vcCreateBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boot_org
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 30 10:22:58 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boot_org
     *
     * @mbg.generated Fri Dec 30 10:22:58 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}