package org.boot.facede.core.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public UserCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVcIdIsNull() {
            addCriterion("VC_ID_ is null");
            return (Criteria) this;
        }

        public Criteria andVcIdIsNotNull() {
            addCriterion("VC_ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcIdEqualTo(String value) {
            addCriterion("VC_ID_ =", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdNotEqualTo(String value) {
            addCriterion("VC_ID_ <>", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdGreaterThan(String value) {
            addCriterion("VC_ID_ >", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdGreaterThanOrEqualTo(String value) {
            addCriterion("VC_ID_ >=", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdLessThan(String value) {
            addCriterion("VC_ID_ <", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdLessThanOrEqualTo(String value) {
            addCriterion("VC_ID_ <=", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdLike(String value) {
            addCriterion("VC_ID_ like", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdNotLike(String value) {
            addCriterion("VC_ID_ not like", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdIn(List<String> values) {
            addCriterion("VC_ID_ in", values, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdNotIn(List<String> values) {
            addCriterion("VC_ID_ not in", values, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdBetween(String value1, String value2) {
            addCriterion("VC_ID_ between", value1, value2, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdNotBetween(String value1, String value2) {
            addCriterion("VC_ID_ not between", value1, value2, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcAccountIsNull() {
            addCriterion("VC_ACCOUNT_ is null");
            return (Criteria) this;
        }

        public Criteria andVcAccountIsNotNull() {
            addCriterion("VC_ACCOUNT_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcAccountEqualTo(String value) {
            addCriterion("VC_ACCOUNT_ =", value, "vcAccount");
            return (Criteria) this;
        }

        public Criteria andVcAccountNotEqualTo(String value) {
            addCriterion("VC_ACCOUNT_ <>", value, "vcAccount");
            return (Criteria) this;
        }

        public Criteria andVcAccountGreaterThan(String value) {
            addCriterion("VC_ACCOUNT_ >", value, "vcAccount");
            return (Criteria) this;
        }

        public Criteria andVcAccountGreaterThanOrEqualTo(String value) {
            addCriterion("VC_ACCOUNT_ >=", value, "vcAccount");
            return (Criteria) this;
        }

        public Criteria andVcAccountLessThan(String value) {
            addCriterion("VC_ACCOUNT_ <", value, "vcAccount");
            return (Criteria) this;
        }

        public Criteria andVcAccountLessThanOrEqualTo(String value) {
            addCriterion("VC_ACCOUNT_ <=", value, "vcAccount");
            return (Criteria) this;
        }

        public Criteria andVcAccountLike(String value) {
            addCriterion("VC_ACCOUNT_ like", value, "vcAccount");
            return (Criteria) this;
        }

        public Criteria andVcAccountNotLike(String value) {
            addCriterion("VC_ACCOUNT_ not like", value, "vcAccount");
            return (Criteria) this;
        }

        public Criteria andVcAccountIn(List<String> values) {
            addCriterion("VC_ACCOUNT_ in", values, "vcAccount");
            return (Criteria) this;
        }

        public Criteria andVcAccountNotIn(List<String> values) {
            addCriterion("VC_ACCOUNT_ not in", values, "vcAccount");
            return (Criteria) this;
        }

        public Criteria andVcAccountBetween(String value1, String value2) {
            addCriterion("VC_ACCOUNT_ between", value1, value2, "vcAccount");
            return (Criteria) this;
        }

        public Criteria andVcAccountNotBetween(String value1, String value2) {
            addCriterion("VC_ACCOUNT_ not between", value1, value2, "vcAccount");
            return (Criteria) this;
        }

        public Criteria andVcPasswordIsNull() {
            addCriterion("VC_PASSWORD_ is null");
            return (Criteria) this;
        }

        public Criteria andVcPasswordIsNotNull() {
            addCriterion("VC_PASSWORD_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcPasswordEqualTo(String value) {
            addCriterion("VC_PASSWORD_ =", value, "vcPassword");
            return (Criteria) this;
        }

        public Criteria andVcPasswordNotEqualTo(String value) {
            addCriterion("VC_PASSWORD_ <>", value, "vcPassword");
            return (Criteria) this;
        }

        public Criteria andVcPasswordGreaterThan(String value) {
            addCriterion("VC_PASSWORD_ >", value, "vcPassword");
            return (Criteria) this;
        }

        public Criteria andVcPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("VC_PASSWORD_ >=", value, "vcPassword");
            return (Criteria) this;
        }

        public Criteria andVcPasswordLessThan(String value) {
            addCriterion("VC_PASSWORD_ <", value, "vcPassword");
            return (Criteria) this;
        }

        public Criteria andVcPasswordLessThanOrEqualTo(String value) {
            addCriterion("VC_PASSWORD_ <=", value, "vcPassword");
            return (Criteria) this;
        }

        public Criteria andVcPasswordLike(String value) {
            addCriterion("VC_PASSWORD_ like", value, "vcPassword");
            return (Criteria) this;
        }

        public Criteria andVcPasswordNotLike(String value) {
            addCriterion("VC_PASSWORD_ not like", value, "vcPassword");
            return (Criteria) this;
        }

        public Criteria andVcPasswordIn(List<String> values) {
            addCriterion("VC_PASSWORD_ in", values, "vcPassword");
            return (Criteria) this;
        }

        public Criteria andVcPasswordNotIn(List<String> values) {
            addCriterion("VC_PASSWORD_ not in", values, "vcPassword");
            return (Criteria) this;
        }

        public Criteria andVcPasswordBetween(String value1, String value2) {
            addCriterion("VC_PASSWORD_ between", value1, value2, "vcPassword");
            return (Criteria) this;
        }

        public Criteria andVcPasswordNotBetween(String value1, String value2) {
            addCriterion("VC_PASSWORD_ not between", value1, value2, "vcPassword");
            return (Criteria) this;
        }

        public Criteria andVcNameIsNull() {
            addCriterion("VC_NAME_ is null");
            return (Criteria) this;
        }

        public Criteria andVcNameIsNotNull() {
            addCriterion("VC_NAME_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcNameEqualTo(String value) {
            addCriterion("VC_NAME_ =", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameNotEqualTo(String value) {
            addCriterion("VC_NAME_ <>", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameGreaterThan(String value) {
            addCriterion("VC_NAME_ >", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameGreaterThanOrEqualTo(String value) {
            addCriterion("VC_NAME_ >=", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameLessThan(String value) {
            addCriterion("VC_NAME_ <", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameLessThanOrEqualTo(String value) {
            addCriterion("VC_NAME_ <=", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameLike(String value) {
            addCriterion("VC_NAME_ like", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameNotLike(String value) {
            addCriterion("VC_NAME_ not like", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameIn(List<String> values) {
            addCriterion("VC_NAME_ in", values, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameNotIn(List<String> values) {
            addCriterion("VC_NAME_ not in", values, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameBetween(String value1, String value2) {
            addCriterion("VC_NAME_ between", value1, value2, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameNotBetween(String value1, String value2) {
            addCriterion("VC_NAME_ not between", value1, value2, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcSexIsNull() {
            addCriterion("VC_SEX_ is null");
            return (Criteria) this;
        }

        public Criteria andVcSexIsNotNull() {
            addCriterion("VC_SEX_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcSexEqualTo(String value) {
            addCriterion("VC_SEX_ =", value, "vcSex");
            return (Criteria) this;
        }

        public Criteria andVcSexNotEqualTo(String value) {
            addCriterion("VC_SEX_ <>", value, "vcSex");
            return (Criteria) this;
        }

        public Criteria andVcSexGreaterThan(String value) {
            addCriterion("VC_SEX_ >", value, "vcSex");
            return (Criteria) this;
        }

        public Criteria andVcSexGreaterThanOrEqualTo(String value) {
            addCriterion("VC_SEX_ >=", value, "vcSex");
            return (Criteria) this;
        }

        public Criteria andVcSexLessThan(String value) {
            addCriterion("VC_SEX_ <", value, "vcSex");
            return (Criteria) this;
        }

        public Criteria andVcSexLessThanOrEqualTo(String value) {
            addCriterion("VC_SEX_ <=", value, "vcSex");
            return (Criteria) this;
        }

        public Criteria andVcSexLike(String value) {
            addCriterion("VC_SEX_ like", value, "vcSex");
            return (Criteria) this;
        }

        public Criteria andVcSexNotLike(String value) {
            addCriterion("VC_SEX_ not like", value, "vcSex");
            return (Criteria) this;
        }

        public Criteria andVcSexIn(List<String> values) {
            addCriterion("VC_SEX_ in", values, "vcSex");
            return (Criteria) this;
        }

        public Criteria andVcSexNotIn(List<String> values) {
            addCriterion("VC_SEX_ not in", values, "vcSex");
            return (Criteria) this;
        }

        public Criteria andVcSexBetween(String value1, String value2) {
            addCriterion("VC_SEX_ between", value1, value2, "vcSex");
            return (Criteria) this;
        }

        public Criteria andVcSexNotBetween(String value1, String value2) {
            addCriterion("VC_SEX_ not between", value1, value2, "vcSex");
            return (Criteria) this;
        }

        public Criteria andVcStatusIsNull() {
            addCriterion("VC_STATUS_ is null");
            return (Criteria) this;
        }

        public Criteria andVcStatusIsNotNull() {
            addCriterion("VC_STATUS_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcStatusEqualTo(String value) {
            addCriterion("VC_STATUS_ =", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusNotEqualTo(String value) {
            addCriterion("VC_STATUS_ <>", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusGreaterThan(String value) {
            addCriterion("VC_STATUS_ >", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusGreaterThanOrEqualTo(String value) {
            addCriterion("VC_STATUS_ >=", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusLessThan(String value) {
            addCriterion("VC_STATUS_ <", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusLessThanOrEqualTo(String value) {
            addCriterion("VC_STATUS_ <=", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusLike(String value) {
            addCriterion("VC_STATUS_ like", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusNotLike(String value) {
            addCriterion("VC_STATUS_ not like", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusIn(List<String> values) {
            addCriterion("VC_STATUS_ in", values, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusNotIn(List<String> values) {
            addCriterion("VC_STATUS_ not in", values, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusBetween(String value1, String value2) {
            addCriterion("VC_STATUS_ between", value1, value2, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusNotBetween(String value1, String value2) {
            addCriterion("VC_STATUS_ not between", value1, value2, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcTypeIsNull() {
            addCriterion("VC_TYPE_ is null");
            return (Criteria) this;
        }

        public Criteria andVcTypeIsNotNull() {
            addCriterion("VC_TYPE_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcTypeEqualTo(String value) {
            addCriterion("VC_TYPE_ =", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeNotEqualTo(String value) {
            addCriterion("VC_TYPE_ <>", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeGreaterThan(String value) {
            addCriterion("VC_TYPE_ >", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeGreaterThanOrEqualTo(String value) {
            addCriterion("VC_TYPE_ >=", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeLessThan(String value) {
            addCriterion("VC_TYPE_ <", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeLessThanOrEqualTo(String value) {
            addCriterion("VC_TYPE_ <=", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeLike(String value) {
            addCriterion("VC_TYPE_ like", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeNotLike(String value) {
            addCriterion("VC_TYPE_ not like", value, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeIn(List<String> values) {
            addCriterion("VC_TYPE_ in", values, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeNotIn(List<String> values) {
            addCriterion("VC_TYPE_ not in", values, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeBetween(String value1, String value2) {
            addCriterion("VC_TYPE_ between", value1, value2, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcTypeNotBetween(String value1, String value2) {
            addCriterion("VC_TYPE_ not between", value1, value2, "vcType");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdIsNull() {
            addCriterion("VC_ORG_ID_ is null");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdIsNotNull() {
            addCriterion("VC_ORG_ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdEqualTo(String value) {
            addCriterion("VC_ORG_ID_ =", value, "vcOrgId");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdNotEqualTo(String value) {
            addCriterion("VC_ORG_ID_ <>", value, "vcOrgId");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdGreaterThan(String value) {
            addCriterion("VC_ORG_ID_ >", value, "vcOrgId");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("VC_ORG_ID_ >=", value, "vcOrgId");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdLessThan(String value) {
            addCriterion("VC_ORG_ID_ <", value, "vcOrgId");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdLessThanOrEqualTo(String value) {
            addCriterion("VC_ORG_ID_ <=", value, "vcOrgId");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdLike(String value) {
            addCriterion("VC_ORG_ID_ like", value, "vcOrgId");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdNotLike(String value) {
            addCriterion("VC_ORG_ID_ not like", value, "vcOrgId");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdIn(List<String> values) {
            addCriterion("VC_ORG_ID_ in", values, "vcOrgId");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdNotIn(List<String> values) {
            addCriterion("VC_ORG_ID_ not in", values, "vcOrgId");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdBetween(String value1, String value2) {
            addCriterion("VC_ORG_ID_ between", value1, value2, "vcOrgId");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdNotBetween(String value1, String value2) {
            addCriterion("VC_ORG_ID_ not between", value1, value2, "vcOrgId");
            return (Criteria) this;
        }

        public Criteria andVcEmailIsNull() {
            addCriterion("VC_EMAIL_ is null");
            return (Criteria) this;
        }

        public Criteria andVcEmailIsNotNull() {
            addCriterion("VC_EMAIL_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcEmailEqualTo(String value) {
            addCriterion("VC_EMAIL_ =", value, "vcEmail");
            return (Criteria) this;
        }

        public Criteria andVcEmailNotEqualTo(String value) {
            addCriterion("VC_EMAIL_ <>", value, "vcEmail");
            return (Criteria) this;
        }

        public Criteria andVcEmailGreaterThan(String value) {
            addCriterion("VC_EMAIL_ >", value, "vcEmail");
            return (Criteria) this;
        }

        public Criteria andVcEmailGreaterThanOrEqualTo(String value) {
            addCriterion("VC_EMAIL_ >=", value, "vcEmail");
            return (Criteria) this;
        }

        public Criteria andVcEmailLessThan(String value) {
            addCriterion("VC_EMAIL_ <", value, "vcEmail");
            return (Criteria) this;
        }

        public Criteria andVcEmailLessThanOrEqualTo(String value) {
            addCriterion("VC_EMAIL_ <=", value, "vcEmail");
            return (Criteria) this;
        }

        public Criteria andVcEmailLike(String value) {
            addCriterion("VC_EMAIL_ like", value, "vcEmail");
            return (Criteria) this;
        }

        public Criteria andVcEmailNotLike(String value) {
            addCriterion("VC_EMAIL_ not like", value, "vcEmail");
            return (Criteria) this;
        }

        public Criteria andVcEmailIn(List<String> values) {
            addCriterion("VC_EMAIL_ in", values, "vcEmail");
            return (Criteria) this;
        }

        public Criteria andVcEmailNotIn(List<String> values) {
            addCriterion("VC_EMAIL_ not in", values, "vcEmail");
            return (Criteria) this;
        }

        public Criteria andVcEmailBetween(String value1, String value2) {
            addCriterion("VC_EMAIL_ between", value1, value2, "vcEmail");
            return (Criteria) this;
        }

        public Criteria andVcEmailNotBetween(String value1, String value2) {
            addCriterion("VC_EMAIL_ not between", value1, value2, "vcEmail");
            return (Criteria) this;
        }

        public Criteria andVcMobileIsNull() {
            addCriterion("VC_MOBILE_ is null");
            return (Criteria) this;
        }

        public Criteria andVcMobileIsNotNull() {
            addCriterion("VC_MOBILE_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcMobileEqualTo(String value) {
            addCriterion("VC_MOBILE_ =", value, "vcMobile");
            return (Criteria) this;
        }

        public Criteria andVcMobileNotEqualTo(String value) {
            addCriterion("VC_MOBILE_ <>", value, "vcMobile");
            return (Criteria) this;
        }

        public Criteria andVcMobileGreaterThan(String value) {
            addCriterion("VC_MOBILE_ >", value, "vcMobile");
            return (Criteria) this;
        }

        public Criteria andVcMobileGreaterThanOrEqualTo(String value) {
            addCriterion("VC_MOBILE_ >=", value, "vcMobile");
            return (Criteria) this;
        }

        public Criteria andVcMobileLessThan(String value) {
            addCriterion("VC_MOBILE_ <", value, "vcMobile");
            return (Criteria) this;
        }

        public Criteria andVcMobileLessThanOrEqualTo(String value) {
            addCriterion("VC_MOBILE_ <=", value, "vcMobile");
            return (Criteria) this;
        }

        public Criteria andVcMobileLike(String value) {
            addCriterion("VC_MOBILE_ like", value, "vcMobile");
            return (Criteria) this;
        }

        public Criteria andVcMobileNotLike(String value) {
            addCriterion("VC_MOBILE_ not like", value, "vcMobile");
            return (Criteria) this;
        }

        public Criteria andVcMobileIn(List<String> values) {
            addCriterion("VC_MOBILE_ in", values, "vcMobile");
            return (Criteria) this;
        }

        public Criteria andVcMobileNotIn(List<String> values) {
            addCriterion("VC_MOBILE_ not in", values, "vcMobile");
            return (Criteria) this;
        }

        public Criteria andVcMobileBetween(String value1, String value2) {
            addCriterion("VC_MOBILE_ between", value1, value2, "vcMobile");
            return (Criteria) this;
        }

        public Criteria andVcMobileNotBetween(String value1, String value2) {
            addCriterion("VC_MOBILE_ not between", value1, value2, "vcMobile");
            return (Criteria) this;
        }

        public Criteria andVcIdnoIsNull() {
            addCriterion("VC_IDNO_ is null");
            return (Criteria) this;
        }

        public Criteria andVcIdnoIsNotNull() {
            addCriterion("VC_IDNO_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcIdnoEqualTo(String value) {
            addCriterion("VC_IDNO_ =", value, "vcIdno");
            return (Criteria) this;
        }

        public Criteria andVcIdnoNotEqualTo(String value) {
            addCriterion("VC_IDNO_ <>", value, "vcIdno");
            return (Criteria) this;
        }

        public Criteria andVcIdnoGreaterThan(String value) {
            addCriterion("VC_IDNO_ >", value, "vcIdno");
            return (Criteria) this;
        }

        public Criteria andVcIdnoGreaterThanOrEqualTo(String value) {
            addCriterion("VC_IDNO_ >=", value, "vcIdno");
            return (Criteria) this;
        }

        public Criteria andVcIdnoLessThan(String value) {
            addCriterion("VC_IDNO_ <", value, "vcIdno");
            return (Criteria) this;
        }

        public Criteria andVcIdnoLessThanOrEqualTo(String value) {
            addCriterion("VC_IDNO_ <=", value, "vcIdno");
            return (Criteria) this;
        }

        public Criteria andVcIdnoLike(String value) {
            addCriterion("VC_IDNO_ like", value, "vcIdno");
            return (Criteria) this;
        }

        public Criteria andVcIdnoNotLike(String value) {
            addCriterion("VC_IDNO_ not like", value, "vcIdno");
            return (Criteria) this;
        }

        public Criteria andVcIdnoIn(List<String> values) {
            addCriterion("VC_IDNO_ in", values, "vcIdno");
            return (Criteria) this;
        }

        public Criteria andVcIdnoNotIn(List<String> values) {
            addCriterion("VC_IDNO_ not in", values, "vcIdno");
            return (Criteria) this;
        }

        public Criteria andVcIdnoBetween(String value1, String value2) {
            addCriterion("VC_IDNO_ between", value1, value2, "vcIdno");
            return (Criteria) this;
        }

        public Criteria andVcIdnoNotBetween(String value1, String value2) {
            addCriterion("VC_IDNO_ not between", value1, value2, "vcIdno");
            return (Criteria) this;
        }

        public Criteria andVcSkinIsNull() {
            addCriterion("VC_SKIN_ is null");
            return (Criteria) this;
        }

        public Criteria andVcSkinIsNotNull() {
            addCriterion("VC_SKIN_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcSkinEqualTo(String value) {
            addCriterion("VC_SKIN_ =", value, "vcSkin");
            return (Criteria) this;
        }

        public Criteria andVcSkinNotEqualTo(String value) {
            addCriterion("VC_SKIN_ <>", value, "vcSkin");
            return (Criteria) this;
        }

        public Criteria andVcSkinGreaterThan(String value) {
            addCriterion("VC_SKIN_ >", value, "vcSkin");
            return (Criteria) this;
        }

        public Criteria andVcSkinGreaterThanOrEqualTo(String value) {
            addCriterion("VC_SKIN_ >=", value, "vcSkin");
            return (Criteria) this;
        }

        public Criteria andVcSkinLessThan(String value) {
            addCriterion("VC_SKIN_ <", value, "vcSkin");
            return (Criteria) this;
        }

        public Criteria andVcSkinLessThanOrEqualTo(String value) {
            addCriterion("VC_SKIN_ <=", value, "vcSkin");
            return (Criteria) this;
        }

        public Criteria andVcSkinLike(String value) {
            addCriterion("VC_SKIN_ like", value, "vcSkin");
            return (Criteria) this;
        }

        public Criteria andVcSkinNotLike(String value) {
            addCriterion("VC_SKIN_ not like", value, "vcSkin");
            return (Criteria) this;
        }

        public Criteria andVcSkinIn(List<String> values) {
            addCriterion("VC_SKIN_ in", values, "vcSkin");
            return (Criteria) this;
        }

        public Criteria andVcSkinNotIn(List<String> values) {
            addCriterion("VC_SKIN_ not in", values, "vcSkin");
            return (Criteria) this;
        }

        public Criteria andVcSkinBetween(String value1, String value2) {
            addCriterion("VC_SKIN_ between", value1, value2, "vcSkin");
            return (Criteria) this;
        }

        public Criteria andVcSkinNotBetween(String value1, String value2) {
            addCriterion("VC_SKIN_ not between", value1, value2, "vcSkin");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeIsNull() {
            addCriterion("VC_BIZ_CODE_ is null");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeIsNotNull() {
            addCriterion("VC_BIZ_CODE_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeEqualTo(String value) {
            addCriterion("VC_BIZ_CODE_ =", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeNotEqualTo(String value) {
            addCriterion("VC_BIZ_CODE_ <>", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeGreaterThan(String value) {
            addCriterion("VC_BIZ_CODE_ >", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeGreaterThanOrEqualTo(String value) {
            addCriterion("VC_BIZ_CODE_ >=", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeLessThan(String value) {
            addCriterion("VC_BIZ_CODE_ <", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeLessThanOrEqualTo(String value) {
            addCriterion("VC_BIZ_CODE_ <=", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeLike(String value) {
            addCriterion("VC_BIZ_CODE_ like", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeNotLike(String value) {
            addCriterion("VC_BIZ_CODE_ not like", value, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeIn(List<String> values) {
            addCriterion("VC_BIZ_CODE_ in", values, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeNotIn(List<String> values) {
            addCriterion("VC_BIZ_CODE_ not in", values, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeBetween(String value1, String value2) {
            addCriterion("VC_BIZ_CODE_ between", value1, value2, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeNotBetween(String value1, String value2) {
            addCriterion("VC_BIZ_CODE_ not between", value1, value2, "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcAddressIsNull() {
            addCriterion("VC_ADDRESS_ is null");
            return (Criteria) this;
        }

        public Criteria andVcAddressIsNotNull() {
            addCriterion("VC_ADDRESS_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcAddressEqualTo(String value) {
            addCriterion("VC_ADDRESS_ =", value, "vcAddress");
            return (Criteria) this;
        }

        public Criteria andVcAddressNotEqualTo(String value) {
            addCriterion("VC_ADDRESS_ <>", value, "vcAddress");
            return (Criteria) this;
        }

        public Criteria andVcAddressGreaterThan(String value) {
            addCriterion("VC_ADDRESS_ >", value, "vcAddress");
            return (Criteria) this;
        }

        public Criteria andVcAddressGreaterThanOrEqualTo(String value) {
            addCriterion("VC_ADDRESS_ >=", value, "vcAddress");
            return (Criteria) this;
        }

        public Criteria andVcAddressLessThan(String value) {
            addCriterion("VC_ADDRESS_ <", value, "vcAddress");
            return (Criteria) this;
        }

        public Criteria andVcAddressLessThanOrEqualTo(String value) {
            addCriterion("VC_ADDRESS_ <=", value, "vcAddress");
            return (Criteria) this;
        }

        public Criteria andVcAddressLike(String value) {
            addCriterion("VC_ADDRESS_ like", value, "vcAddress");
            return (Criteria) this;
        }

        public Criteria andVcAddressNotLike(String value) {
            addCriterion("VC_ADDRESS_ not like", value, "vcAddress");
            return (Criteria) this;
        }

        public Criteria andVcAddressIn(List<String> values) {
            addCriterion("VC_ADDRESS_ in", values, "vcAddress");
            return (Criteria) this;
        }

        public Criteria andVcAddressNotIn(List<String> values) {
            addCriterion("VC_ADDRESS_ not in", values, "vcAddress");
            return (Criteria) this;
        }

        public Criteria andVcAddressBetween(String value1, String value2) {
            addCriterion("VC_ADDRESS_ between", value1, value2, "vcAddress");
            return (Criteria) this;
        }

        public Criteria andVcAddressNotBetween(String value1, String value2) {
            addCriterion("VC_ADDRESS_ not between", value1, value2, "vcAddress");
            return (Criteria) this;
        }

        public Criteria andVcRemarkIsNull() {
            addCriterion("VC_REMARK_ is null");
            return (Criteria) this;
        }

        public Criteria andVcRemarkIsNotNull() {
            addCriterion("VC_REMARK_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcRemarkEqualTo(String value) {
            addCriterion("VC_REMARK_ =", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkNotEqualTo(String value) {
            addCriterion("VC_REMARK_ <>", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkGreaterThan(String value) {
            addCriterion("VC_REMARK_ >", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("VC_REMARK_ >=", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkLessThan(String value) {
            addCriterion("VC_REMARK_ <", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkLessThanOrEqualTo(String value) {
            addCriterion("VC_REMARK_ <=", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkLike(String value) {
            addCriterion("VC_REMARK_ like", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkNotLike(String value) {
            addCriterion("VC_REMARK_ not like", value, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkIn(List<String> values) {
            addCriterion("VC_REMARK_ in", values, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkNotIn(List<String> values) {
            addCriterion("VC_REMARK_ not in", values, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkBetween(String value1, String value2) {
            addCriterion("VC_REMARK_ between", value1, value2, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcRemarkNotBetween(String value1, String value2) {
            addCriterion("VC_REMARK_ not between", value1, value2, "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcIsDelIsNull() {
            addCriterion("VC_IS_DEL_ is null");
            return (Criteria) this;
        }

        public Criteria andVcIsDelIsNotNull() {
            addCriterion("VC_IS_DEL_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcIsDelEqualTo(String value) {
            addCriterion("VC_IS_DEL_ =", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelNotEqualTo(String value) {
            addCriterion("VC_IS_DEL_ <>", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelGreaterThan(String value) {
            addCriterion("VC_IS_DEL_ >", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelGreaterThanOrEqualTo(String value) {
            addCriterion("VC_IS_DEL_ >=", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelLessThan(String value) {
            addCriterion("VC_IS_DEL_ <", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelLessThanOrEqualTo(String value) {
            addCriterion("VC_IS_DEL_ <=", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelLike(String value) {
            addCriterion("VC_IS_DEL_ like", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelNotLike(String value) {
            addCriterion("VC_IS_DEL_ not like", value, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelIn(List<String> values) {
            addCriterion("VC_IS_DEL_ in", values, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelNotIn(List<String> values) {
            addCriterion("VC_IS_DEL_ not in", values, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelBetween(String value1, String value2) {
            addCriterion("VC_IS_DEL_ between", value1, value2, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcIsDelNotBetween(String value1, String value2) {
            addCriterion("VC_IS_DEL_ not between", value1, value2, "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andDtCreateTimeIsNull() {
            addCriterion("DT_CREATE_TIME_ is null");
            return (Criteria) this;
        }

        public Criteria andDtCreateTimeIsNotNull() {
            addCriterion("DT_CREATE_TIME_ is not null");
            return (Criteria) this;
        }

        public Criteria andDtCreateTimeEqualTo(Date value) {
            addCriterion("DT_CREATE_TIME_ =", value, "dtCreateTime");
            return (Criteria) this;
        }

        public Criteria andDtCreateTimeNotEqualTo(Date value) {
            addCriterion("DT_CREATE_TIME_ <>", value, "dtCreateTime");
            return (Criteria) this;
        }

        public Criteria andDtCreateTimeGreaterThan(Date value) {
            addCriterion("DT_CREATE_TIME_ >", value, "dtCreateTime");
            return (Criteria) this;
        }

        public Criteria andDtCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DT_CREATE_TIME_ >=", value, "dtCreateTime");
            return (Criteria) this;
        }

        public Criteria andDtCreateTimeLessThan(Date value) {
            addCriterion("DT_CREATE_TIME_ <", value, "dtCreateTime");
            return (Criteria) this;
        }

        public Criteria andDtCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("DT_CREATE_TIME_ <=", value, "dtCreateTime");
            return (Criteria) this;
        }

        public Criteria andDtCreateTimeIn(List<Date> values) {
            addCriterion("DT_CREATE_TIME_ in", values, "dtCreateTime");
            return (Criteria) this;
        }

        public Criteria andDtCreateTimeNotIn(List<Date> values) {
            addCriterion("DT_CREATE_TIME_ not in", values, "dtCreateTime");
            return (Criteria) this;
        }

        public Criteria andDtCreateTimeBetween(Date value1, Date value2) {
            addCriterion("DT_CREATE_TIME_ between", value1, value2, "dtCreateTime");
            return (Criteria) this;
        }

        public Criteria andDtCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("DT_CREATE_TIME_ not between", value1, value2, "dtCreateTime");
            return (Criteria) this;
        }

        public Criteria andVcCreateByIsNull() {
            addCriterion("VC_CREATE_BY_ is null");
            return (Criteria) this;
        }

        public Criteria andVcCreateByIsNotNull() {
            addCriterion("VC_CREATE_BY_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcCreateByEqualTo(String value) {
            addCriterion("VC_CREATE_BY_ =", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByNotEqualTo(String value) {
            addCriterion("VC_CREATE_BY_ <>", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByGreaterThan(String value) {
            addCriterion("VC_CREATE_BY_ >", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("VC_CREATE_BY_ >=", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByLessThan(String value) {
            addCriterion("VC_CREATE_BY_ <", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByLessThanOrEqualTo(String value) {
            addCriterion("VC_CREATE_BY_ <=", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByLike(String value) {
            addCriterion("VC_CREATE_BY_ like", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByNotLike(String value) {
            addCriterion("VC_CREATE_BY_ not like", value, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByIn(List<String> values) {
            addCriterion("VC_CREATE_BY_ in", values, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByNotIn(List<String> values) {
            addCriterion("VC_CREATE_BY_ not in", values, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByBetween(String value1, String value2) {
            addCriterion("VC_CREATE_BY_ between", value1, value2, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcCreateByNotBetween(String value1, String value2) {
            addCriterion("VC_CREATE_BY_ not between", value1, value2, "vcCreateBy");
            return (Criteria) this;
        }

        public Criteria andVcIdLikeInsensitive(String value) {
            addCriterion("upper(VC_ID_) like", value.toUpperCase(), "vcId");
            return (Criteria) this;
        }

        public Criteria andVcAccountLikeInsensitive(String value) {
            addCriterion("upper(VC_ACCOUNT_) like", value.toUpperCase(), "vcAccount");
            return (Criteria) this;
        }

        public Criteria andVcPasswordLikeInsensitive(String value) {
            addCriterion("upper(VC_PASSWORD_) like", value.toUpperCase(), "vcPassword");
            return (Criteria) this;
        }

        public Criteria andVcNameLikeInsensitive(String value) {
            addCriterion("upper(VC_NAME_) like", value.toUpperCase(), "vcName");
            return (Criteria) this;
        }

        public Criteria andVcSexLikeInsensitive(String value) {
            addCriterion("upper(VC_SEX_) like", value.toUpperCase(), "vcSex");
            return (Criteria) this;
        }

        public Criteria andVcStatusLikeInsensitive(String value) {
            addCriterion("upper(VC_STATUS_) like", value.toUpperCase(), "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcTypeLikeInsensitive(String value) {
            addCriterion("upper(VC_TYPE_) like", value.toUpperCase(), "vcType");
            return (Criteria) this;
        }

        public Criteria andVcOrgIdLikeInsensitive(String value) {
            addCriterion("upper(VC_ORG_ID_) like", value.toUpperCase(), "vcOrgId");
            return (Criteria) this;
        }

        public Criteria andVcEmailLikeInsensitive(String value) {
            addCriterion("upper(VC_EMAIL_) like", value.toUpperCase(), "vcEmail");
            return (Criteria) this;
        }

        public Criteria andVcMobileLikeInsensitive(String value) {
            addCriterion("upper(VC_MOBILE_) like", value.toUpperCase(), "vcMobile");
            return (Criteria) this;
        }

        public Criteria andVcIdnoLikeInsensitive(String value) {
            addCriterion("upper(VC_IDNO_) like", value.toUpperCase(), "vcIdno");
            return (Criteria) this;
        }

        public Criteria andVcSkinLikeInsensitive(String value) {
            addCriterion("upper(VC_SKIN_) like", value.toUpperCase(), "vcSkin");
            return (Criteria) this;
        }

        public Criteria andVcBizCodeLikeInsensitive(String value) {
            addCriterion("upper(VC_BIZ_CODE_) like", value.toUpperCase(), "vcBizCode");
            return (Criteria) this;
        }

        public Criteria andVcAddressLikeInsensitive(String value) {
            addCriterion("upper(VC_ADDRESS_) like", value.toUpperCase(), "vcAddress");
            return (Criteria) this;
        }

        public Criteria andVcRemarkLikeInsensitive(String value) {
            addCriterion("upper(VC_REMARK_) like", value.toUpperCase(), "vcRemark");
            return (Criteria) this;
        }

        public Criteria andVcIsDelLikeInsensitive(String value) {
            addCriterion("upper(VC_IS_DEL_) like", value.toUpperCase(), "vcIsDel");
            return (Criteria) this;
        }

        public Criteria andVcCreateByLikeInsensitive(String value) {
            addCriterion("upper(VC_CREATE_BY_) like", value.toUpperCase(), "vcCreateBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boot_user
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 30 10:22:59 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}