package org.boot.facede.core.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_ACCOUNT_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_PASSWORD_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_NAME_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_SEX_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_STATUS_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_TYPE_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_ORG_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_EMAIL_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_MOBILE_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_IDNO_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcIdno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_SKIN_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcSkin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_BIZ_CODE_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcBizCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_ADDRESS_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_REMARK_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_IS_DEL_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcIsDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.DT_CREATE_TIME_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private Date dtCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.VC_CREATE_BY_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private String vcCreateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_ID_
     *
     * @return the value of boot_user.VC_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcId() {
        return vcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_ID_
     *
     * @param vcId the value for boot_user.VC_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcId(String vcId) {
        this.vcId = vcId == null ? null : vcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_ACCOUNT_
     *
     * @return the value of boot_user.VC_ACCOUNT_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcAccount() {
        return vcAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_ACCOUNT_
     *
     * @param vcAccount the value for boot_user.VC_ACCOUNT_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcAccount(String vcAccount) {
        this.vcAccount = vcAccount == null ? null : vcAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_PASSWORD_
     *
     * @return the value of boot_user.VC_PASSWORD_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcPassword() {
        return vcPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_PASSWORD_
     *
     * @param vcPassword the value for boot_user.VC_PASSWORD_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcPassword(String vcPassword) {
        this.vcPassword = vcPassword == null ? null : vcPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_NAME_
     *
     * @return the value of boot_user.VC_NAME_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcName() {
        return vcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_NAME_
     *
     * @param vcName the value for boot_user.VC_NAME_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcName(String vcName) {
        this.vcName = vcName == null ? null : vcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_SEX_
     *
     * @return the value of boot_user.VC_SEX_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcSex() {
        return vcSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_SEX_
     *
     * @param vcSex the value for boot_user.VC_SEX_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcSex(String vcSex) {
        this.vcSex = vcSex == null ? null : vcSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_STATUS_
     *
     * @return the value of boot_user.VC_STATUS_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcStatus() {
        return vcStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_STATUS_
     *
     * @param vcStatus the value for boot_user.VC_STATUS_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcStatus(String vcStatus) {
        this.vcStatus = vcStatus == null ? null : vcStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_TYPE_
     *
     * @return the value of boot_user.VC_TYPE_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcType() {
        return vcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_TYPE_
     *
     * @param vcType the value for boot_user.VC_TYPE_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcType(String vcType) {
        this.vcType = vcType == null ? null : vcType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_ORG_ID_
     *
     * @return the value of boot_user.VC_ORG_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcOrgId() {
        return vcOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_ORG_ID_
     *
     * @param vcOrgId the value for boot_user.VC_ORG_ID_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcOrgId(String vcOrgId) {
        this.vcOrgId = vcOrgId == null ? null : vcOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_EMAIL_
     *
     * @return the value of boot_user.VC_EMAIL_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcEmail() {
        return vcEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_EMAIL_
     *
     * @param vcEmail the value for boot_user.VC_EMAIL_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcEmail(String vcEmail) {
        this.vcEmail = vcEmail == null ? null : vcEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_MOBILE_
     *
     * @return the value of boot_user.VC_MOBILE_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcMobile() {
        return vcMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_MOBILE_
     *
     * @param vcMobile the value for boot_user.VC_MOBILE_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcMobile(String vcMobile) {
        this.vcMobile = vcMobile == null ? null : vcMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_IDNO_
     *
     * @return the value of boot_user.VC_IDNO_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcIdno() {
        return vcIdno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_IDNO_
     *
     * @param vcIdno the value for boot_user.VC_IDNO_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcIdno(String vcIdno) {
        this.vcIdno = vcIdno == null ? null : vcIdno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_SKIN_
     *
     * @return the value of boot_user.VC_SKIN_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcSkin() {
        return vcSkin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_SKIN_
     *
     * @param vcSkin the value for boot_user.VC_SKIN_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcSkin(String vcSkin) {
        this.vcSkin = vcSkin == null ? null : vcSkin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_BIZ_CODE_
     *
     * @return the value of boot_user.VC_BIZ_CODE_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcBizCode() {
        return vcBizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_BIZ_CODE_
     *
     * @param vcBizCode the value for boot_user.VC_BIZ_CODE_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcBizCode(String vcBizCode) {
        this.vcBizCode = vcBizCode == null ? null : vcBizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_ADDRESS_
     *
     * @return the value of boot_user.VC_ADDRESS_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcAddress() {
        return vcAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_ADDRESS_
     *
     * @param vcAddress the value for boot_user.VC_ADDRESS_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcAddress(String vcAddress) {
        this.vcAddress = vcAddress == null ? null : vcAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_REMARK_
     *
     * @return the value of boot_user.VC_REMARK_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcRemark() {
        return vcRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_REMARK_
     *
     * @param vcRemark the value for boot_user.VC_REMARK_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcRemark(String vcRemark) {
        this.vcRemark = vcRemark == null ? null : vcRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_IS_DEL_
     *
     * @return the value of boot_user.VC_IS_DEL_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcIsDel() {
        return vcIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_IS_DEL_
     *
     * @param vcIsDel the value for boot_user.VC_IS_DEL_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcIsDel(String vcIsDel) {
        this.vcIsDel = vcIsDel == null ? null : vcIsDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.DT_CREATE_TIME_
     *
     * @return the value of boot_user.DT_CREATE_TIME_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public Date getDtCreateTime() {
        return dtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.DT_CREATE_TIME_
     *
     * @param dtCreateTime the value for boot_user.DT_CREATE_TIME_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setDtCreateTime(Date dtCreateTime) {
        this.dtCreateTime = dtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.VC_CREATE_BY_
     *
     * @return the value of boot_user.VC_CREATE_BY_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public String getVcCreateBy() {
        return vcCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.VC_CREATE_BY_
     *
     * @param vcCreateBy the value for boot_user.VC_CREATE_BY_
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    public void setVcCreateBy(String vcCreateBy) {
        this.vcCreateBy = vcCreateBy == null ? null : vcCreateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vcId=").append(vcId);
        sb.append(", vcAccount=").append(vcAccount);
        sb.append(", vcPassword=").append(vcPassword);
        sb.append(", vcName=").append(vcName);
        sb.append(", vcSex=").append(vcSex);
        sb.append(", vcStatus=").append(vcStatus);
        sb.append(", vcType=").append(vcType);
        sb.append(", vcOrgId=").append(vcOrgId);
        sb.append(", vcEmail=").append(vcEmail);
        sb.append(", vcMobile=").append(vcMobile);
        sb.append(", vcIdno=").append(vcIdno);
        sb.append(", vcSkin=").append(vcSkin);
        sb.append(", vcBizCode=").append(vcBizCode);
        sb.append(", vcAddress=").append(vcAddress);
        sb.append(", vcRemark=").append(vcRemark);
        sb.append(", vcIsDel=").append(vcIsDel);
        sb.append(", dtCreateTime=").append(dtCreateTime);
        sb.append(", vcCreateBy=").append(vcCreateBy);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getVcId() == null ? other.getVcId() == null : this.getVcId().equals(other.getVcId()))
            && (this.getVcAccount() == null ? other.getVcAccount() == null : this.getVcAccount().equals(other.getVcAccount()))
            && (this.getVcPassword() == null ? other.getVcPassword() == null : this.getVcPassword().equals(other.getVcPassword()))
            && (this.getVcName() == null ? other.getVcName() == null : this.getVcName().equals(other.getVcName()))
            && (this.getVcSex() == null ? other.getVcSex() == null : this.getVcSex().equals(other.getVcSex()))
            && (this.getVcStatus() == null ? other.getVcStatus() == null : this.getVcStatus().equals(other.getVcStatus()))
            && (this.getVcType() == null ? other.getVcType() == null : this.getVcType().equals(other.getVcType()))
            && (this.getVcOrgId() == null ? other.getVcOrgId() == null : this.getVcOrgId().equals(other.getVcOrgId()))
            && (this.getVcEmail() == null ? other.getVcEmail() == null : this.getVcEmail().equals(other.getVcEmail()))
            && (this.getVcMobile() == null ? other.getVcMobile() == null : this.getVcMobile().equals(other.getVcMobile()))
            && (this.getVcIdno() == null ? other.getVcIdno() == null : this.getVcIdno().equals(other.getVcIdno()))
            && (this.getVcSkin() == null ? other.getVcSkin() == null : this.getVcSkin().equals(other.getVcSkin()))
            && (this.getVcBizCode() == null ? other.getVcBizCode() == null : this.getVcBizCode().equals(other.getVcBizCode()))
            && (this.getVcAddress() == null ? other.getVcAddress() == null : this.getVcAddress().equals(other.getVcAddress()))
            && (this.getVcRemark() == null ? other.getVcRemark() == null : this.getVcRemark().equals(other.getVcRemark()))
            && (this.getVcIsDel() == null ? other.getVcIsDel() == null : this.getVcIsDel().equals(other.getVcIsDel()))
            && (this.getDtCreateTime() == null ? other.getDtCreateTime() == null : this.getDtCreateTime().equals(other.getDtCreateTime()))
            && (this.getVcCreateBy() == null ? other.getVcCreateBy() == null : this.getVcCreateBy().equals(other.getVcCreateBy()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot_user
     *
     * @mbg.generated Fri Dec 30 10:22:59 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getVcId() == null) ? 0 : getVcId().hashCode());
        result = prime * result + ((getVcAccount() == null) ? 0 : getVcAccount().hashCode());
        result = prime * result + ((getVcPassword() == null) ? 0 : getVcPassword().hashCode());
        result = prime * result + ((getVcName() == null) ? 0 : getVcName().hashCode());
        result = prime * result + ((getVcSex() == null) ? 0 : getVcSex().hashCode());
        result = prime * result + ((getVcStatus() == null) ? 0 : getVcStatus().hashCode());
        result = prime * result + ((getVcType() == null) ? 0 : getVcType().hashCode());
        result = prime * result + ((getVcOrgId() == null) ? 0 : getVcOrgId().hashCode());
        result = prime * result + ((getVcEmail() == null) ? 0 : getVcEmail().hashCode());
        result = prime * result + ((getVcMobile() == null) ? 0 : getVcMobile().hashCode());
        result = prime * result + ((getVcIdno() == null) ? 0 : getVcIdno().hashCode());
        result = prime * result + ((getVcSkin() == null) ? 0 : getVcSkin().hashCode());
        result = prime * result + ((getVcBizCode() == null) ? 0 : getVcBizCode().hashCode());
        result = prime * result + ((getVcAddress() == null) ? 0 : getVcAddress().hashCode());
        result = prime * result + ((getVcRemark() == null) ? 0 : getVcRemark().hashCode());
        result = prime * result + ((getVcIsDel() == null) ? 0 : getVcIsDel().hashCode());
        result = prime * result + ((getDtCreateTime() == null) ? 0 : getDtCreateTime().hashCode());
        result = prime * result + ((getVcCreateBy() == null) ? 0 : getVcCreateBy().hashCode());
        return result;
    }
}