package org.boot.service.privilege.dao.base;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.boot.facede.privilege.model.RoleButton;
import org.boot.facede.privilege.model.RoleButtonCriteria;
import org.boot.service.privilege.dao.extension.RoleButtonExtensionMapper;

@Mapper
public interface RoleButtonMapper extends RoleButtonExtensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    int countByExample(RoleButtonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    int deleteByExample(RoleButtonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String rbid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    int insert(RoleButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    int insertSelective(RoleButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    List<RoleButton> selectByExampleWithRowbounds(RoleButtonCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    List<RoleButton> selectByExample(RoleButtonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    RoleButton selectByPrimaryKey(String rbid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoleButton record, @Param("example") RoleButtonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoleButton record, @Param("example") RoleButtonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleButton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ROLE_BUTTON
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleButton record);
}