package org.boot.facede.activiti.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApplicationCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public ApplicationCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVcIdIsNull() {
            addCriterion("VC_ID_ is null");
            return (Criteria) this;
        }

        public Criteria andVcIdIsNotNull() {
            addCriterion("VC_ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcIdEqualTo(String value) {
            addCriterion("VC_ID_ =", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdNotEqualTo(String value) {
            addCriterion("VC_ID_ <>", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdGreaterThan(String value) {
            addCriterion("VC_ID_ >", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdGreaterThanOrEqualTo(String value) {
            addCriterion("VC_ID_ >=", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdLessThan(String value) {
            addCriterion("VC_ID_ <", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdLessThanOrEqualTo(String value) {
            addCriterion("VC_ID_ <=", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdLike(String value) {
            addCriterion("VC_ID_ like", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdNotLike(String value) {
            addCriterion("VC_ID_ not like", value, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdIn(List<String> values) {
            addCriterion("VC_ID_ in", values, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdNotIn(List<String> values) {
            addCriterion("VC_ID_ not in", values, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdBetween(String value1, String value2) {
            addCriterion("VC_ID_ between", value1, value2, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcIdNotBetween(String value1, String value2) {
            addCriterion("VC_ID_ not between", value1, value2, "vcId");
            return (Criteria) this;
        }

        public Criteria andVcNameIsNull() {
            addCriterion("VC_NAME_ is null");
            return (Criteria) this;
        }

        public Criteria andVcNameIsNotNull() {
            addCriterion("VC_NAME_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcNameEqualTo(String value) {
            addCriterion("VC_NAME_ =", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameNotEqualTo(String value) {
            addCriterion("VC_NAME_ <>", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameGreaterThan(String value) {
            addCriterion("VC_NAME_ >", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameGreaterThanOrEqualTo(String value) {
            addCriterion("VC_NAME_ >=", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameLessThan(String value) {
            addCriterion("VC_NAME_ <", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameLessThanOrEqualTo(String value) {
            addCriterion("VC_NAME_ <=", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameLike(String value) {
            addCriterion("VC_NAME_ like", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameNotLike(String value) {
            addCriterion("VC_NAME_ not like", value, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameIn(List<String> values) {
            addCriterion("VC_NAME_ in", values, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameNotIn(List<String> values) {
            addCriterion("VC_NAME_ not in", values, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameBetween(String value1, String value2) {
            addCriterion("VC_NAME_ between", value1, value2, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcNameNotBetween(String value1, String value2) {
            addCriterion("VC_NAME_ not between", value1, value2, "vcName");
            return (Criteria) this;
        }

        public Criteria andVcUserIdIsNull() {
            addCriterion("VC_USER_ID_ is null");
            return (Criteria) this;
        }

        public Criteria andVcUserIdIsNotNull() {
            addCriterion("VC_USER_ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcUserIdEqualTo(String value) {
            addCriterion("VC_USER_ID_ =", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdNotEqualTo(String value) {
            addCriterion("VC_USER_ID_ <>", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdGreaterThan(String value) {
            addCriterion("VC_USER_ID_ >", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("VC_USER_ID_ >=", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdLessThan(String value) {
            addCriterion("VC_USER_ID_ <", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdLessThanOrEqualTo(String value) {
            addCriterion("VC_USER_ID_ <=", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdLike(String value) {
            addCriterion("VC_USER_ID_ like", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdNotLike(String value) {
            addCriterion("VC_USER_ID_ not like", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdIn(List<String> values) {
            addCriterion("VC_USER_ID_ in", values, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdNotIn(List<String> values) {
            addCriterion("VC_USER_ID_ not in", values, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdBetween(String value1, String value2) {
            addCriterion("VC_USER_ID_ between", value1, value2, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdNotBetween(String value1, String value2) {
            addCriterion("VC_USER_ID_ not between", value1, value2, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andDtCtimeIsNull() {
            addCriterion("DT_CTIME_ is null");
            return (Criteria) this;
        }

        public Criteria andDtCtimeIsNotNull() {
            addCriterion("DT_CTIME_ is not null");
            return (Criteria) this;
        }

        public Criteria andDtCtimeEqualTo(Date value) {
            addCriterion("DT_CTIME_ =", value, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeNotEqualTo(Date value) {
            addCriterion("DT_CTIME_ <>", value, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeGreaterThan(Date value) {
            addCriterion("DT_CTIME_ >", value, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DT_CTIME_ >=", value, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeLessThan(Date value) {
            addCriterion("DT_CTIME_ <", value, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeLessThanOrEqualTo(Date value) {
            addCriterion("DT_CTIME_ <=", value, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeIn(List<Date> values) {
            addCriterion("DT_CTIME_ in", values, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeNotIn(List<Date> values) {
            addCriterion("DT_CTIME_ not in", values, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeBetween(Date value1, Date value2) {
            addCriterion("DT_CTIME_ between", value1, value2, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeNotBetween(Date value1, Date value2) {
            addCriterion("DT_CTIME_ not between", value1, value2, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andVcStatusIsNull() {
            addCriterion("VC_STATUS_ is null");
            return (Criteria) this;
        }

        public Criteria andVcStatusIsNotNull() {
            addCriterion("VC_STATUS_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcStatusEqualTo(String value) {
            addCriterion("VC_STATUS_ =", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusNotEqualTo(String value) {
            addCriterion("VC_STATUS_ <>", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusGreaterThan(String value) {
            addCriterion("VC_STATUS_ >", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusGreaterThanOrEqualTo(String value) {
            addCriterion("VC_STATUS_ >=", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusLessThan(String value) {
            addCriterion("VC_STATUS_ <", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusLessThanOrEqualTo(String value) {
            addCriterion("VC_STATUS_ <=", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusLike(String value) {
            addCriterion("VC_STATUS_ like", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusNotLike(String value) {
            addCriterion("VC_STATUS_ not like", value, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusIn(List<String> values) {
            addCriterion("VC_STATUS_ in", values, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusNotIn(List<String> values) {
            addCriterion("VC_STATUS_ not in", values, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusBetween(String value1, String value2) {
            addCriterion("VC_STATUS_ between", value1, value2, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcStatusNotBetween(String value1, String value2) {
            addCriterion("VC_STATUS_ not between", value1, value2, "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcFilePathIsNull() {
            addCriterion("VC_FILE_PATH_ is null");
            return (Criteria) this;
        }

        public Criteria andVcFilePathIsNotNull() {
            addCriterion("VC_FILE_PATH_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcFilePathEqualTo(String value) {
            addCriterion("VC_FILE_PATH_ =", value, "vcFilePath");
            return (Criteria) this;
        }

        public Criteria andVcFilePathNotEqualTo(String value) {
            addCriterion("VC_FILE_PATH_ <>", value, "vcFilePath");
            return (Criteria) this;
        }

        public Criteria andVcFilePathGreaterThan(String value) {
            addCriterion("VC_FILE_PATH_ >", value, "vcFilePath");
            return (Criteria) this;
        }

        public Criteria andVcFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("VC_FILE_PATH_ >=", value, "vcFilePath");
            return (Criteria) this;
        }

        public Criteria andVcFilePathLessThan(String value) {
            addCriterion("VC_FILE_PATH_ <", value, "vcFilePath");
            return (Criteria) this;
        }

        public Criteria andVcFilePathLessThanOrEqualTo(String value) {
            addCriterion("VC_FILE_PATH_ <=", value, "vcFilePath");
            return (Criteria) this;
        }

        public Criteria andVcFilePathLike(String value) {
            addCriterion("VC_FILE_PATH_ like", value, "vcFilePath");
            return (Criteria) this;
        }

        public Criteria andVcFilePathNotLike(String value) {
            addCriterion("VC_FILE_PATH_ not like", value, "vcFilePath");
            return (Criteria) this;
        }

        public Criteria andVcFilePathIn(List<String> values) {
            addCriterion("VC_FILE_PATH_ in", values, "vcFilePath");
            return (Criteria) this;
        }

        public Criteria andVcFilePathNotIn(List<String> values) {
            addCriterion("VC_FILE_PATH_ not in", values, "vcFilePath");
            return (Criteria) this;
        }

        public Criteria andVcFilePathBetween(String value1, String value2) {
            addCriterion("VC_FILE_PATH_ between", value1, value2, "vcFilePath");
            return (Criteria) this;
        }

        public Criteria andVcFilePathNotBetween(String value1, String value2) {
            addCriterion("VC_FILE_PATH_ not between", value1, value2, "vcFilePath");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdIsNull() {
            addCriterion("VC_TEMPLATE_ID_ is null");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdIsNotNull() {
            addCriterion("VC_TEMPLATE_ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdEqualTo(String value) {
            addCriterion("VC_TEMPLATE_ID_ =", value, "vcTemplateId");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdNotEqualTo(String value) {
            addCriterion("VC_TEMPLATE_ID_ <>", value, "vcTemplateId");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdGreaterThan(String value) {
            addCriterion("VC_TEMPLATE_ID_ >", value, "vcTemplateId");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdGreaterThanOrEqualTo(String value) {
            addCriterion("VC_TEMPLATE_ID_ >=", value, "vcTemplateId");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdLessThan(String value) {
            addCriterion("VC_TEMPLATE_ID_ <", value, "vcTemplateId");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdLessThanOrEqualTo(String value) {
            addCriterion("VC_TEMPLATE_ID_ <=", value, "vcTemplateId");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdLike(String value) {
            addCriterion("VC_TEMPLATE_ID_ like", value, "vcTemplateId");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdNotLike(String value) {
            addCriterion("VC_TEMPLATE_ID_ not like", value, "vcTemplateId");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdIn(List<String> values) {
            addCriterion("VC_TEMPLATE_ID_ in", values, "vcTemplateId");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdNotIn(List<String> values) {
            addCriterion("VC_TEMPLATE_ID_ not in", values, "vcTemplateId");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdBetween(String value1, String value2) {
            addCriterion("VC_TEMPLATE_ID_ between", value1, value2, "vcTemplateId");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdNotBetween(String value1, String value2) {
            addCriterion("VC_TEMPLATE_ID_ not between", value1, value2, "vcTemplateId");
            return (Criteria) this;
        }

        public Criteria andVcIdLikeInsensitive(String value) {
            addCriterion("upper(VC_ID_) like", value.toUpperCase(), "vcId");
            return (Criteria) this;
        }

        public Criteria andVcNameLikeInsensitive(String value) {
            addCriterion("upper(VC_NAME_) like", value.toUpperCase(), "vcName");
            return (Criteria) this;
        }

        public Criteria andVcUserIdLikeInsensitive(String value) {
            addCriterion("upper(VC_USER_ID_) like", value.toUpperCase(), "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcStatusLikeInsensitive(String value) {
            addCriterion("upper(VC_STATUS_) like", value.toUpperCase(), "vcStatus");
            return (Criteria) this;
        }

        public Criteria andVcFilePathLikeInsensitive(String value) {
            addCriterion("upper(VC_FILE_PATH_) like", value.toUpperCase(), "vcFilePath");
            return (Criteria) this;
        }

        public Criteria andVcTemplateIdLikeInsensitive(String value) {
            addCriterion("upper(VC_TEMPLATE_ID_) like", value.toUpperCase(), "vcTemplateId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 26 14:01:03 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}