package org.boot.facede.activiti.model;

import java.io.Serializable;
import java.util.Date;

public class Application implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_AS_APPLICATION.VC_ID_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    private String vcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_AS_APPLICATION.VC_NAME_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    private String vcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_AS_APPLICATION.VC_USER_ID_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    private String vcUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_AS_APPLICATION.DT_CTIME_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    private Date dtCtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_AS_APPLICATION.VC_STATUS_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    private String vcStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_AS_APPLICATION.VC_FILE_PATH_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    private String vcFilePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACT_AS_APPLICATION.VC_TEMPLATE_ID_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    private String vcTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_AS_APPLICATION.VC_ID_
     *
     * @return the value of ACT_AS_APPLICATION.VC_ID_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public String getVcId() {
        return vcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_AS_APPLICATION.VC_ID_
     *
     * @param vcId the value for ACT_AS_APPLICATION.VC_ID_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void setVcId(String vcId) {
        this.vcId = vcId == null ? null : vcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_AS_APPLICATION.VC_NAME_
     *
     * @return the value of ACT_AS_APPLICATION.VC_NAME_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public String getVcName() {
        return vcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_AS_APPLICATION.VC_NAME_
     *
     * @param vcName the value for ACT_AS_APPLICATION.VC_NAME_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void setVcName(String vcName) {
        this.vcName = vcName == null ? null : vcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_AS_APPLICATION.VC_USER_ID_
     *
     * @return the value of ACT_AS_APPLICATION.VC_USER_ID_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public String getVcUserId() {
        return vcUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_AS_APPLICATION.VC_USER_ID_
     *
     * @param vcUserId the value for ACT_AS_APPLICATION.VC_USER_ID_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void setVcUserId(String vcUserId) {
        this.vcUserId = vcUserId == null ? null : vcUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_AS_APPLICATION.DT_CTIME_
     *
     * @return the value of ACT_AS_APPLICATION.DT_CTIME_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public Date getDtCtime() {
        return dtCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_AS_APPLICATION.DT_CTIME_
     *
     * @param dtCtime the value for ACT_AS_APPLICATION.DT_CTIME_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void setDtCtime(Date dtCtime) {
        this.dtCtime = dtCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_AS_APPLICATION.VC_STATUS_
     *
     * @return the value of ACT_AS_APPLICATION.VC_STATUS_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public String getVcStatus() {
        return vcStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_AS_APPLICATION.VC_STATUS_
     *
     * @param vcStatus the value for ACT_AS_APPLICATION.VC_STATUS_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void setVcStatus(String vcStatus) {
        this.vcStatus = vcStatus == null ? null : vcStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_AS_APPLICATION.VC_FILE_PATH_
     *
     * @return the value of ACT_AS_APPLICATION.VC_FILE_PATH_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public String getVcFilePath() {
        return vcFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_AS_APPLICATION.VC_FILE_PATH_
     *
     * @param vcFilePath the value for ACT_AS_APPLICATION.VC_FILE_PATH_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void setVcFilePath(String vcFilePath) {
        this.vcFilePath = vcFilePath == null ? null : vcFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACT_AS_APPLICATION.VC_TEMPLATE_ID_
     *
     * @return the value of ACT_AS_APPLICATION.VC_TEMPLATE_ID_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public String getVcTemplateId() {
        return vcTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACT_AS_APPLICATION.VC_TEMPLATE_ID_
     *
     * @param vcTemplateId the value for ACT_AS_APPLICATION.VC_TEMPLATE_ID_
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void setVcTemplateId(String vcTemplateId) {
        this.vcTemplateId = vcTemplateId == null ? null : vcTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vcId=").append(vcId);
        sb.append(", vcName=").append(vcName);
        sb.append(", vcUserId=").append(vcUserId);
        sb.append(", dtCtime=").append(dtCtime);
        sb.append(", vcStatus=").append(vcStatus);
        sb.append(", vcFilePath=").append(vcFilePath);
        sb.append(", vcTemplateId=").append(vcTemplateId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Application other = (Application) that;
        return (this.getVcId() == null ? other.getVcId() == null : this.getVcId().equals(other.getVcId()))
            && (this.getVcName() == null ? other.getVcName() == null : this.getVcName().equals(other.getVcName()))
            && (this.getVcUserId() == null ? other.getVcUserId() == null : this.getVcUserId().equals(other.getVcUserId()))
            && (this.getDtCtime() == null ? other.getDtCtime() == null : this.getDtCtime().equals(other.getDtCtime()))
            && (this.getVcStatus() == null ? other.getVcStatus() == null : this.getVcStatus().equals(other.getVcStatus()))
            && (this.getVcFilePath() == null ? other.getVcFilePath() == null : this.getVcFilePath().equals(other.getVcFilePath()))
            && (this.getVcTemplateId() == null ? other.getVcTemplateId() == null : this.getVcTemplateId().equals(other.getVcTemplateId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPLICATION
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getVcId() == null) ? 0 : getVcId().hashCode());
        result = prime * result + ((getVcName() == null) ? 0 : getVcName().hashCode());
        result = prime * result + ((getVcUserId() == null) ? 0 : getVcUserId().hashCode());
        result = prime * result + ((getDtCtime() == null) ? 0 : getDtCtime().hashCode());
        result = prime * result + ((getVcStatus() == null) ? 0 : getVcStatus().hashCode());
        result = prime * result + ((getVcFilePath() == null) ? 0 : getVcFilePath().hashCode());
        result = prime * result + ((getVcTemplateId() == null) ? 0 : getVcTemplateId().hashCode());
        return result;
    }
}