package org.boot.facede.activiti.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApproveInfoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public ApproveInfoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLoIdIsNull() {
            addCriterion("LO_ID_ is null");
            return (Criteria) this;
        }

        public Criteria andLoIdIsNotNull() {
            addCriterion("LO_ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andLoIdEqualTo(Long value) {
            addCriterion("LO_ID_ =", value, "loId");
            return (Criteria) this;
        }

        public Criteria andLoIdNotEqualTo(Long value) {
            addCriterion("LO_ID_ <>", value, "loId");
            return (Criteria) this;
        }

        public Criteria andLoIdGreaterThan(Long value) {
            addCriterion("LO_ID_ >", value, "loId");
            return (Criteria) this;
        }

        public Criteria andLoIdGreaterThanOrEqualTo(Long value) {
            addCriterion("LO_ID_ >=", value, "loId");
            return (Criteria) this;
        }

        public Criteria andLoIdLessThan(Long value) {
            addCriterion("LO_ID_ <", value, "loId");
            return (Criteria) this;
        }

        public Criteria andLoIdLessThanOrEqualTo(Long value) {
            addCriterion("LO_ID_ <=", value, "loId");
            return (Criteria) this;
        }

        public Criteria andLoIdIn(List<Long> values) {
            addCriterion("LO_ID_ in", values, "loId");
            return (Criteria) this;
        }

        public Criteria andLoIdNotIn(List<Long> values) {
            addCriterion("LO_ID_ not in", values, "loId");
            return (Criteria) this;
        }

        public Criteria andLoIdBetween(Long value1, Long value2) {
            addCriterion("LO_ID_ between", value1, value2, "loId");
            return (Criteria) this;
        }

        public Criteria andLoIdNotBetween(Long value1, Long value2) {
            addCriterion("LO_ID_ not between", value1, value2, "loId");
            return (Criteria) this;
        }

        public Criteria andDtCtimeIsNull() {
            addCriterion("DT_CTIME_ is null");
            return (Criteria) this;
        }

        public Criteria andDtCtimeIsNotNull() {
            addCriterion("DT_CTIME_ is not null");
            return (Criteria) this;
        }

        public Criteria andDtCtimeEqualTo(Date value) {
            addCriterion("DT_CTIME_ =", value, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeNotEqualTo(Date value) {
            addCriterion("DT_CTIME_ <>", value, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeGreaterThan(Date value) {
            addCriterion("DT_CTIME_ >", value, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("DT_CTIME_ >=", value, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeLessThan(Date value) {
            addCriterion("DT_CTIME_ <", value, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeLessThanOrEqualTo(Date value) {
            addCriterion("DT_CTIME_ <=", value, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeIn(List<Date> values) {
            addCriterion("DT_CTIME_ in", values, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeNotIn(List<Date> values) {
            addCriterion("DT_CTIME_ not in", values, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeBetween(Date value1, Date value2) {
            addCriterion("DT_CTIME_ between", value1, value2, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andDtCtimeNotBetween(Date value1, Date value2) {
            addCriterion("DT_CTIME_ not between", value1, value2, "dtCtime");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdIsNull() {
            addCriterion("VC_APPLICATION_ID_ is null");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdIsNotNull() {
            addCriterion("VC_APPLICATION_ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdEqualTo(String value) {
            addCriterion("VC_APPLICATION_ID_ =", value, "vcApplicationId");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdNotEqualTo(String value) {
            addCriterion("VC_APPLICATION_ID_ <>", value, "vcApplicationId");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdGreaterThan(String value) {
            addCriterion("VC_APPLICATION_ID_ >", value, "vcApplicationId");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdGreaterThanOrEqualTo(String value) {
            addCriterion("VC_APPLICATION_ID_ >=", value, "vcApplicationId");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdLessThan(String value) {
            addCriterion("VC_APPLICATION_ID_ <", value, "vcApplicationId");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdLessThanOrEqualTo(String value) {
            addCriterion("VC_APPLICATION_ID_ <=", value, "vcApplicationId");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdLike(String value) {
            addCriterion("VC_APPLICATION_ID_ like", value, "vcApplicationId");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdNotLike(String value) {
            addCriterion("VC_APPLICATION_ID_ not like", value, "vcApplicationId");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdIn(List<String> values) {
            addCriterion("VC_APPLICATION_ID_ in", values, "vcApplicationId");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdNotIn(List<String> values) {
            addCriterion("VC_APPLICATION_ID_ not in", values, "vcApplicationId");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdBetween(String value1, String value2) {
            addCriterion("VC_APPLICATION_ID_ between", value1, value2, "vcApplicationId");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdNotBetween(String value1, String value2) {
            addCriterion("VC_APPLICATION_ID_ not between", value1, value2, "vcApplicationId");
            return (Criteria) this;
        }

        public Criteria andVcResultIsNull() {
            addCriterion("VC_RESULT_ is null");
            return (Criteria) this;
        }

        public Criteria andVcResultIsNotNull() {
            addCriterion("VC_RESULT_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcResultEqualTo(String value) {
            addCriterion("VC_RESULT_ =", value, "vcResult");
            return (Criteria) this;
        }

        public Criteria andVcResultNotEqualTo(String value) {
            addCriterion("VC_RESULT_ <>", value, "vcResult");
            return (Criteria) this;
        }

        public Criteria andVcResultGreaterThan(String value) {
            addCriterion("VC_RESULT_ >", value, "vcResult");
            return (Criteria) this;
        }

        public Criteria andVcResultGreaterThanOrEqualTo(String value) {
            addCriterion("VC_RESULT_ >=", value, "vcResult");
            return (Criteria) this;
        }

        public Criteria andVcResultLessThan(String value) {
            addCriterion("VC_RESULT_ <", value, "vcResult");
            return (Criteria) this;
        }

        public Criteria andVcResultLessThanOrEqualTo(String value) {
            addCriterion("VC_RESULT_ <=", value, "vcResult");
            return (Criteria) this;
        }

        public Criteria andVcResultLike(String value) {
            addCriterion("VC_RESULT_ like", value, "vcResult");
            return (Criteria) this;
        }

        public Criteria andVcResultNotLike(String value) {
            addCriterion("VC_RESULT_ not like", value, "vcResult");
            return (Criteria) this;
        }

        public Criteria andVcResultIn(List<String> values) {
            addCriterion("VC_RESULT_ in", values, "vcResult");
            return (Criteria) this;
        }

        public Criteria andVcResultNotIn(List<String> values) {
            addCriterion("VC_RESULT_ not in", values, "vcResult");
            return (Criteria) this;
        }

        public Criteria andVcResultBetween(String value1, String value2) {
            addCriterion("VC_RESULT_ between", value1, value2, "vcResult");
            return (Criteria) this;
        }

        public Criteria andVcResultNotBetween(String value1, String value2) {
            addCriterion("VC_RESULT_ not between", value1, value2, "vcResult");
            return (Criteria) this;
        }

        public Criteria andVcUserIdIsNull() {
            addCriterion("VC_USER_ID_ is null");
            return (Criteria) this;
        }

        public Criteria andVcUserIdIsNotNull() {
            addCriterion("VC_USER_ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andVcUserIdEqualTo(String value) {
            addCriterion("VC_USER_ID_ =", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdNotEqualTo(String value) {
            addCriterion("VC_USER_ID_ <>", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdGreaterThan(String value) {
            addCriterion("VC_USER_ID_ >", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("VC_USER_ID_ >=", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdLessThan(String value) {
            addCriterion("VC_USER_ID_ <", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdLessThanOrEqualTo(String value) {
            addCriterion("VC_USER_ID_ <=", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdLike(String value) {
            addCriterion("VC_USER_ID_ like", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdNotLike(String value) {
            addCriterion("VC_USER_ID_ not like", value, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdIn(List<String> values) {
            addCriterion("VC_USER_ID_ in", values, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdNotIn(List<String> values) {
            addCriterion("VC_USER_ID_ not in", values, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdBetween(String value1, String value2) {
            addCriterion("VC_USER_ID_ between", value1, value2, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcUserIdNotBetween(String value1, String value2) {
            addCriterion("VC_USER_ID_ not between", value1, value2, "vcUserId");
            return (Criteria) this;
        }

        public Criteria andVcApplicationIdLikeInsensitive(String value) {
            addCriterion("upper(VC_APPLICATION_ID_) like", value.toUpperCase(), "vcApplicationId");
            return (Criteria) this;
        }

        public Criteria andVcResultLikeInsensitive(String value) {
            addCriterion("upper(VC_RESULT_) like", value.toUpperCase(), "vcResult");
            return (Criteria) this;
        }

        public Criteria andVcUserIdLikeInsensitive(String value) {
            addCriterion("upper(VC_USER_ID_) like", value.toUpperCase(), "vcUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 26 14:01:03 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACT_AS_APPROVE_INFO
     *
     * @mbg.generated Mon Dec 26 14:01:03 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}